@include('console.nav', ['title' => ucwords(str_replace('-', ' ', $section))])

@if($section === 'struktur-organisasi')
    <div class="d-flex flex-wrap justify-content-between align-items-center gap-3 mb-4"><p class="text-secondary mb-0">Kelola unit, jabatan, serta hubungan induk dalam bagan struktur organisasi.</p><button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#unitCreate"><i class="fa fa-plus me-1"></i>Tambah Unit</button></div>
    <div class="card overflow-hidden"><div class="p-3 border-bottom d-flex justify-content-between"><h2 class="h5 mb-0"><i class="fa fa-sitemap text-primary me-2"></i>Daftar Unit Struktur</h2><span class="badge text-bg-secondary">{{ $units->total() }} data</span></div><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Unit / Jabatan</th><th>Kunci Unit</th><th>Induk</th><th>Urutan</th><th>Status</th><th class="text-end">Aksi</th></tr></thead><tbody>@forelse($units as $unit)<tr><td><strong>{{ $unit->name }}</strong></td><td><code>{{ $unit->unit_key }}</code></td><td>{{ $unit->parent_key ?: '-' }}</td><td>{{ $unit->sort_order }}</td><td><span class="badge text-bg-{{ $unit->is_active ? 'success' : 'secondary' }}">{{ $unit->is_active ? 'Aktif' : 'Nonaktif' }}</span></td><td class="text-end"><button class="btn btn-sm btn-outline-primary" data-bs-toggle="modal" data-bs-target="#unit{{ $unit->id }}"><i class="fa fa-pen"></i></button><form method="post" action="/console/kelola-web/struktur-organisasi/{{ $unit->id }}" class="d-inline">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger js-swal-delete" data-message="Hapus unit {{ $unit->name }}?"><i class="fa fa-trash"></i></button></form></td></tr>@empty<tr><td colspan="6" class="text-center text-secondary py-5">Belum ada unit struktur organisasi.</td></tr>@endforelse</tbody></table></div></div><div class="mt-3">{{ $units->links() }}</div>
    @include('console.web.unit-form', ['id' => 'unitCreate', 'action' => '/console/kelola-web/struktur-organisasi', 'unit' => null, 'parentUnits' => $parentUnits])
    @foreach($units as $unit) @include('console.web.unit-form', ['id' => 'unit'.$unit->id, 'action' => '/console/kelola-web/struktur-organisasi/'.$unit->id, 'unit' => $unit, 'parentUnits' => $parentUnits]) @endforeach
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>

@elseif($section === 'profil-dinas')
    @php
        $defaultMilestones = [
            ['title' => 'Pembentukan Dinas', 'description' => 'Perangkat daerah yang melaksanakan urusan pemerintahan bidang perumahan rakyat dan kawasan permukiman.'],
            ['title' => 'Pengembangan Layanan', 'description' => 'Peningkatan pelayanan perumahan, penanganan kawasan, dan dukungan bagi masyarakat berpenghasilan rendah.'],
            ['title' => 'Transformasi Pelayanan', 'description' => 'Penguatan program strategis dan informasi terpadu bagi pembangunan permukiman berkelanjutan.'],
        ];
        $milestones = old('milestone_title') ? collect(old('milestone_title'))->values()->map(fn ($title, $index) => ['title' => $title, 'description' => old('milestone_description')[$index] ?? ''])->all() : ($setting?->profile_milestones ?: $defaultMilestones);
        $defaultServices = ['Perencanaan Permukiman','Pembangunan Perumahan','Penataan Kawasan','Pembiayaan Perumahan','Pengawasan Pembangunan'];
        $services = old('service_scope') ?: ($setting?->service_scopes ?: $defaultServices);
    @endphp
    <style>.profile-admin-section{padding:19px;margin-bottom:20px;border:1px solid #deebef;border-radius:13px;background:#fbfdfd}.profile-admin-section h3{margin:0 0 15px;color:#294d5f;font-size:1rem;font-weight:800}.profile-admin-section h3 i{color:#1c779f}.repeat-item{padding:15px;margin-bottom:10px;border:1px solid #e0ebee;border-radius:10px;background:#fff}.repeat-item:last-child{margin-bottom:0}.profile-admin-section .repeat-item{display:none}.profile-admin-section:has(input[name="service_scope[]"]){display:none}</style>
    <div class="card p-4">
        <div class="mb-4"><h2 class="h5 mb-1">Kelola Konten Profil Dinas</h2><p class="text-secondary small mb-0">Seluruh bagian pada halaman Profil Dinas frontend dapat diperbarui dari formulir ini.</p></div>
        <form method="post" action="/console/kelola-web/profil-dinas">@csrf @method('PUT')
            <section class="profile-admin-section"><h3><i class="fa fa-building me-2"></i>Identitas Tampilan</h3><div class="row g-3"><div class="col-md-8"><label class="form-label">Nama Instansi</label><input name="agency_name" class="form-control" value="{{ old('agency_name', $setting?->agency_name) }}" required></div><div class="col-md-4"><label class="form-label">Nama Singkat</label><input name="short_name" class="form-control" value="{{ old('short_name', $setting?->short_name) }}"></div><div class="col-12"><label class="form-label">Tagline Profil</label><input name="profile_tagline" class="form-control" value="{{ old('profile_tagline', $setting?->profile_tagline) }}" placeholder="Contoh: Melayani pembangunan perumahan dan kawasan permukiman yang layak."></div></div></section>
            <section class="profile-admin-section"><h3><i class="fa fa-align-left me-2"></i>Deskripsi dan Arah Pelayanan</h3><div class="row g-3"><div class="col-12"><label class="form-label">Tentang Dinas</label><textarea name="about" class="form-control" rows="6">{{ old('about', $setting?->about) }}</textarea></div><div class="col-12"><label class="form-label">Arah Pelayanan</label><textarea name="profile_direction" class="form-control" rows="4" placeholder="Arah pelayanan yang tampil pada halaman profil.">{{ old('profile_direction', $setting?->profile_direction ?: $setting?->mission) }}</textarea></div></div></section>
            <section class="profile-admin-section"><h3><i class="fa fa-clock-rotate-left me-2"></i>Sejarah dan Tahapan Perjalanan</h3><div class="mb-3"><label class="form-label">Sejarah Singkat</label><textarea name="history" class="form-control" rows="6">{{ old('history', $setting?->history) }}</textarea></div>@foreach($milestones as $index => $milestone)<div class="repeat-item"><strong class="small text-primary d-block mb-2">Tahapan {{ $index + 1 }}</strong><div class="row g-3"><div class="col-md-4"><label class="form-label">Judul Tahapan</label><input name="milestone_title[]" class="form-control" value="{{ $milestone['title'] ?? '' }}"></div><div class="col-md-8"><label class="form-label">Deskripsi Tahapan</label><input name="milestone_description[]" class="form-control" value="{{ $milestone['description'] ?? '' }}"></div></div></div>@endforeach</section>
            <section class="profile-admin-section"><h3><i class="fa fa-handshake-angle me-2"></i>Ruang Lingkup Layanan</h3><div class="row g-3">@foreach($services as $service)<div class="col-md-4"><label class="form-label">Layanan</label><input name="service_scope[]" class="form-control" value="{{ $service }}"></div>@endforeach</div></section>
            <div class="d-flex justify-content-end gap-2"><a href="/profil-dinas" target="_blank" class="btn btn-light border"><i class="fa fa-arrow-up-right-from-square me-1"></i>Lihat Frontend</a><button class="btn btn-primary px-4"><i class="fa fa-floppy-disk me-2"></i>Simpan Profil Dinas</button></div>
        </form>
    </div>

@elseif($section === 'tugas-fungsi')
    @php
        $defaultFunctions = [
            ['title' => 'Perumusan Kebijakan', 'items' => ['Perumusan kebijakan di bidang perumahan dan kawasan permukiman.']],
            ['title' => 'Pembinaan', 'items' => ['Pembinaan teknis di bidang perumahan dan kawasan permukiman.', 'Pembinaan unit pelaksana teknis dinas.', 'Pembinaan kelompok jabatan fungsional.']],
            ['title' => 'Pelaksanaan Program', 'items' => ['Pelaksanaan kebijakan di bidang perumahan dan kawasan permukiman.', 'Pelaksanaan administrasi dinas perumahan dan kawasan permukiman sesuai lingkup tugasnya.', 'Pelaksanaan evaluasi dan pelaporan di bidang perumahan dan kawasan permukiman.', 'Pelaksanaan fungsi lain yang diberikan oleh Gubernur terkait tugas dan fungsinya.']],
        ];
        $functions = old('duty_function_title') ? collect(old('duty_function_title'))->map(fn ($title, $index) => ['title' => $title, 'items' => preg_split('/\r\n|\r|\n/', old('duty_function_items')[$index] ?? '')])->all() : ($setting?->duty_functions ?: $defaultFunctions);
    @endphp
    <div class="card p-4"><div class="mb-4"><h2 class="h5 mb-1">Kelola Tugas Pokok dan Fungsi</h2><p class="small text-secondary mb-0">Ubah tugas pokok dan daftar fungsi yang ditampilkan pada halaman frontend.</p></div><form method="post" action="/console/kelola-web/tugas-fungsi">@csrf @method('PUT')<div class="mb-4"><label class="form-label">Tugas Pokok</label><textarea name="duties" class="form-control" rows="5">{{ old('duties', $setting?->duties) }}</textarea></div><div class="d-flex align-items-center justify-content-between mb-3"><h3 class="h6 mb-0 text-primary"><i class="fa fa-list-check me-2"></i>Kelompok Fungsi</h3><small class="text-secondary">Satu poin fungsi per baris.</small></div>@foreach($functions as $index => $function)<div class="border rounded-3 p-3 mb-3 bg-light"><strong class="small text-secondary d-block mb-2">KELOMPOK FUNGSI {{ $index + 1 }}</strong><div class="row g-3"><div class="col-md-4"><label class="form-label">Judul Fungsi</label><input name="duty_function_title[]" class="form-control" value="{{ $function['title'] ?? '' }}"></div><div class="col-md-8"><label class="form-label">Poin Fungsi</label><textarea name="duty_function_items[]" class="form-control" rows="5">{{ implode(PHP_EOL, $function['items'] ?? []) }}</textarea></div></div></div>@endforeach<div class="d-flex justify-content-end gap-2"><a href="/tugas-pokok-fungsi" target="_blank" class="btn btn-light border">Lihat Frontend</a><button class="btn btn-primary px-4"><i class="fa fa-floppy-disk me-2"></i>Simpan Tugas dan Fungsi</button></div></form></div>

@else
    <div class="card p-4"><h2 class="h5">Visi Misi</h2><form method="post" action="/console/kelola-web/visi-misi" class="row g-3">@csrf @method('PUT')<div class="col-12"><label class="form-label">Visi</label><textarea name="vision" class="form-control" rows="4">{{ old('vision', $setting?->vision) }}</textarea></div><div class="col-12"><label class="form-label">Misi (satu poin per baris)</label><textarea name="mission" class="form-control" rows="7">{{ old('mission', $setting?->mission) }}</textarea></div><div><button class="btn btn-primary">Simpan Perubahan</button></div></form></div>
@endif

@include('console.end')
