@extends('frontend.layouts.public')
@section('content')
<section class="public-hero"><div class="container"><p class="text-warning fw-bold mb-2">DINAS PKP MALUKU</p><h1 class="display-6 fw-bold">{{ $title }}</h1></div></section>
<main class="container py-5">
@if($page==='visi-misi')<div class="row g-4"><div class="col-md-6"><article class="content-card p-4 bg-white h-100"><h2 class="h3"><i class="fas fa-eye text-primary me-2"></i>Visi</h2><p class="lh-lg">{{ $setting?->vision }}</p></article></div><div class="col-md-6"><article class="content-card p-4 bg-white h-100"><h2 class="h3"><i class="fas fa-bullseye text-primary me-2"></i>Misi</h2><p class="lh-lg">{{ $setting?->mission }}</p></article></div></div>
@elseif($page==='tugas-pokok-fungsi')<article class="content-card p-4 p-lg-5 bg-white"><h2 class="h3">Tugas Pokok dan Fungsi</h2><p class="lh-lg">{{ $setting?->duties ?: 'Melaksanakan urusan pemerintahan bidang perumahan rakyat dan kawasan permukiman sesuai ketentuan peraturan perundang-undangan.' }}</p></article>
@elseif(in_array($page,['struktur-organisasi','profil-pejabat']))<div class="row g-4">@forelse($officials as $official)<div class="col-md-6 col-lg-4"><article class="content-card bg-white p-4 h-100 text-center"><img src="{{ $official->photo_path ? asset($official->photo_path) : asset('assets/img/user.png') }}" class="rounded-circle mb-3" style="width:110px;height:110px;object-fit:cover"><h2 class="h5">{{ $official->name }}</h2><p class="text-primary mb-1">{{ $official->position }}</p><small class="text-secondary">{{ $official->echelon }}</small>@if($page==='profil-pejabat')<p class="small mt-3 text-start">{{ $official->bio }}</p>@endif</article></div>@empty<p>Data pejabat belum tersedia.</p>@endforelse</div>
@elseif($page==='agenda-kegiatan')<div class="row g-4">@forelse($agendas as $agenda)<div class="col-md-6 col-lg-4"><article class="content-card bg-white p-4 h-100"><span class="badge text-bg-primary">{{ optional($agenda->start_date)->format('d M Y') }}</span><h2 class="h5 mt-3">{{ $agenda->title }}</h2><p>{{ $agenda->description }}</p><small><i class="fas fa-location-dot me-2"></i>{{ $agenda->location }}</small></article></div>@empty<p>Agenda belum tersedia.</p>@endforelse</div>
@elseif($page==='program-kegiatan')<div class="row g-4">@forelse($programs as $program)<div class="col-md-6 col-lg-4"><article class="content-card bg-white p-4 h-100"><span class="badge text-bg-primary">{{ $program->fiscal_year }}</span><h2 class="h5 mt-3">{{ $program->name }}</h2><p>{{ $program->description }}</p><small>{{ $program->type?->name }} · {{ ucfirst($program->status) }}</small></article></div>@empty<p>Program belum tersedia.</p>@endforelse</div>
@elseif($page==='berita')<div class="row g-4">@forelse($posts as $post)<div class="col-md-6 col-lg-4"><article class="content-card bg-white h-100 overflow-hidden">@if($post->cover_image)<img src="{{ asset($post->cover_image) }}" class="w-100" style="height:210px;object-fit:cover">@endif<div class="p-4"><small class="text-secondary">{{ optional($post->published_at)->format('d M Y') }}</small><h2 class="h5 mt-2">{{ $post->title }}</h2><p>{{ $post->excerpt }}</p></div></article></div>@empty<p>Berita belum tersedia.</p>@endforelse</div>
@elseif($page==='geomap')<div class="content-card bg-white p-4"><div class="row g-3 mb-3"><div class="col-md-4"><select id="regencyFilter" class="form-select"><option value="">Semua Kabupaten</option>@foreach($regencies as $regency)<option value="{{ $regency->id }}">{{ $regency->name }}</option>@endforeach</select></div><div class="col-md-4"><select id="villageFilter" class="form-select"><option value="">Semua Desa</option></select></div><div class="col-md-4"><select id="layerFilter" class="form-select"><option value="default">Default</option><option value="terrain">Terrain</option><option value="satellite">Satelit</option><option value="hybrid">Hybrid</option></select></div></div><div id="map" style="height:520px;border-radius:14px"></div></div><link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"><script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script><script>const map=L.map('map').setView([-3.7,128.2],7);let layer,features;const layers={default:'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',terrain:'https://{s}.tile.opentopomap.org/{z}/{x}/{y}.png',satellite:'https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',hybrid:'https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}'};function draw(){if(layer)map.removeLayer(layer);layer=L.tileLayer(layers[layerFilter.value],{maxZoom:19}).addTo(map);fetch('/geomap-data?regency_id='+regencyFilter.value+'&village_id='+villageFilter.value).then(r=>r.json()).then(data=>{if(features)map.removeLayer(features);features=L.geoJSON(data,{onEachFeature:(f,l)=>l.bindPopup('<b>'+f.properties.name+'</b><br>'+ (f.properties.regency||'')+'<br>'+ (f.properties.village||''))}).addTo(map)})}layerFilter.onchange=draw;regencyFilter.onchange=draw;draw();</script>
@elseif($page==='galeri')<div class="row g-4">@forelse($galleries as $gallery)<div class="col-md-6 col-lg-4"><article class="content-card bg-white overflow-hidden h-100">@if($gallery->image_path)<img src="{{ asset($gallery->image_path) }}" class="w-100" style="height:220px;object-fit:cover">@endif<div class="p-3"><h2 class="h5">{{ $gallery->title }}</h2><p class="small">{{ $gallery->description }}</p></div></article></div>@empty<p>Galeri belum tersedia.</p>@endforelse</div>
@elseif(in_array($page,['peraturan','informasi','unduhan']))<div class="row g-4">@forelse($documents->where('category',$page==='unduhan'?'unduhan':$page) as $document)<div class="col-md-6"><article class="content-card bg-white p-4"><h2 class="h5">{{ $document->title }}</h2><p>{{ $document->description }}</p><a href="{{ asset($document->file_path) }}" class="btn btn-outline-primary" target="_blank"><i class="fas fa-download me-2"></i>Unduh Dokumen</a></article></div>@empty<p>Dokumen belum tersedia.</p>@endforelse</div>
@elseif($page==='kontak')<div class="row g-4"><div class="col-lg-7"><article class="content-card p-4 bg-white"><h2 class="h4">Hubungi Kami</h2><p><i class="fas fa-map-marker-alt text-primary me-2"></i>{{ $setting?->address }}</p><p><i class="fas fa-phone text-primary me-2"></i>{{ $setting?->phone }}</p><p><i class="fas fa-envelope text-primary me-2"></i>{{ $setting?->email }}</p></article></div><div class="col-lg-5"><article class="content-card p-4 bg-white"><h2 class="h4">Media Sosial</h2>@foreach(($setting?->social_links ?? []) as $name=>$url)<p><a href="{{ $url }}" target="_blank"><i class="fab fa-{{ $name==='facebook'?'facebook-f':$name }} me-2"></i>{{ ucfirst($name) }}</a></p>@endforeach</article></div></div>
@endif
</main>
@endsection
