@include('console.nav',['title'=>'GeoJSON Wilayah'])

<div class="d-flex flex-wrap justify-content-between align-items-center gap-3 mb-4">
    <div><p class="text-secondary mb-0">Kelola arsiran wilayah yang digunakan pada GeoMAP.</p><small class="text-secondary">Mendukung file <strong>.json</strong>, <strong>.geojson</strong>, dan JavaScript hasil ekspor peta.</small></div>
    <div class="d-flex gap-2"><button class="btn btn-outline-primary" data-bs-toggle="modal" data-bs-target="#importJson"><i class="fa fa-file-import me-1"></i>Import File</button><button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#manualJson"><i class="fa fa-plus me-1"></i>Tambah Wilayah</button></div>
</div>

<form class="card card-body mb-4" method="get">
    <div class="row g-3 align-items-end">
        <div class="col-md-5"><label class="form-label">Cari wilayah</label><input type="search" name="cari" value="{{ request('cari') }}" class="form-control" placeholder="Nama kawasan, desa, atau wilayah"></div>
        <div class="col-md-4"><label class="form-label">Kabupaten / Kota</label><select name="regency_id" class="form-select"><option value="">Semua kabupaten / kota</option>@foreach($regencies as $regency)<option value="{{ $regency->id }}" @selected((string) request('regency_id')===(string) $regency->id)>{{ $regency->name }}</option>@endforeach</select></div>
        <div class="col-md-3 d-flex gap-2"><button class="btn btn-primary"><i class="fa fa-filter me-1"></i>Filter</button><a href="/console/program-mbbr/geojson-wilayah" class="btn btn-light border">Reset</a></div>
    </div>
</form>

<div class="card overflow-hidden"><div class="p-3 border-bottom d-flex justify-content-between align-items-center"><h2 class="h5 mb-0"><i class="fa fa-map-location-dot text-primary me-2"></i>Daftar Wilayah</h2><span class="badge text-bg-secondary">{{ $areas->total() }} data</span></div><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Wilayah</th><th>Kabupaten / Kota</th><th>Jenis Geometri</th><th class="text-end">Aksi</th></tr></thead><tbody>@forelse($areas as $area)<tr><td><strong>{{ $area->name }}</strong><br><small class="text-secondary">Diperbarui {{ $area->updated_at->format('d M Y') }}</small></td><td>{{ $area->regency?->name ?: '-' }}</td><td><span class="badge text-bg-light border text-dark">{{ $area->geojson['type'] ?? 'GeoJSON' }}</span></td><td class="text-end"><button class="btn btn-sm btn-outline-primary" title="Edit" data-bs-toggle="modal" data-bs-target="#area{{ $area->id }}"><i class="fa fa-pen"></i></button><form method="post" action="/console/program-mbbr/geojson-wilayah/{{ $area->id }}" class="d-inline">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger js-swal-delete" data-message="Hapus wilayah {{ $area->name }}?" title="Hapus"><i class="fa fa-trash"></i></button></form></td></tr>@empty<tr><td colspan="4" class="text-center text-secondary py-5">Data wilayah belum tersedia.</td></tr>@endforelse</tbody></table></div></div>
<div class="mt-3">{{ $areas->links() }}</div>

@include('console.mbbr.area-form',['id'=>'manualJson','action'=>'/console/program-mbbr/geojson-wilayah','area'=>null,'regencies'=>$regencies])
@foreach($areas as $area)
    @include('console.mbbr.area-form',['id'=>'area'.$area->id,'action'=>'/console/program-mbbr/geojson-wilayah/'.$area->id,'area'=>$area,'regencies'=>$regencies])
@endforeach

<div class="modal fade" id="importJson" tabindex="-1"><div class="modal-dialog"><form method="post" action="/console/program-mbbr/geojson-wilayah/import" enctype="multipart/form-data" class="modal-content">@csrf<div class="modal-header"><h2 class="fs-5"><i class="fa fa-file-import me-2"></i>Import Wilayah</h2><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><label class="form-label">File GeoJSON atau JavaScript</label><input type="file" name="file" accept=".json,.geojson,.js,application/json,application/javascript" class="form-control" required><p class="small text-secondary mt-2 mb-3">Gunakan file GeoJSON biasa atau file JavaScript dengan format <code>var nama_wilayah = {...};</code>.</p><label class="form-label">Kabupaten / Kota</label><select name="regency_id" class="form-select"><option value="">Tidak ditentukan</option>@foreach($regencies as $regency)<option value="{{ $regency->id }}">{{ $regency->name }}</option>@endforeach</select><label class="form-label mt-3">Warna arsiran hasil import</label><div class="d-flex gap-2 align-items-center"><input type="color" name="color" value="#2563eb" class="form-control form-control-color"><small class="text-secondary">Diterapkan ke semua wilayah pada file ini.</small></div></div><div class="modal-footer"><button type="button" class="btn btn-light" data-bs-dismiss="modal">Batal</button><button class="btn btn-primary">Import Wilayah</button></div></form></div></div>

<script>document.addEventListener('DOMContentLoaded',()=>{const loading=(title,text)=>Swal.fire({title,text,allowOutsideClick:false,allowEscapeKey:false,didOpen:()=>Swal.showLoading()});const form=document.querySelector('form[action="/console/program-mbbr/geojson-wilayah/import"]');if(form)form.addEventListener('submit',event=>{event.preventDefault();const button=form.querySelector('button[type="submit"],button:not([type])');if(button){button.disabled=true;button.innerHTML='<span class="spinner-border spinner-border-sm me-2"></span>Mengimpor...'}loading('Sedang mengimpor wilayah','Mohon tunggu, file sedang diproses.');setTimeout(()=>form.submit(),120)});document.querySelectorAll('.pagination a').forEach(link=>link.addEventListener('click',()=>loading('Memuat data wilayah','Mengambil 5 data pada halaman berikutnya.')));})</script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
@include('console.end')
