@include('console.nav',['title'=>'Jenis MBBR'])

<div class="d-flex justify-content-between align-items-center mb-4"><div><p class="text-secondary mb-0">Kelola kategori utama Program MBBR.</p></div><button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#typeCreate"><i class="fa fa-plus me-1"></i>Tambah Jenis</button></div>
<div class="card overflow-hidden"><div class="p-3 border-bottom d-flex justify-content-between"><h2 class="h5 mb-0">Daftar Jenis MBBR</h2><span class="badge text-bg-secondary">{{ $types->count() }} jenis</span></div><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Kode</th><th>Nama Jenis</th><th>Keterangan</th><th>Sub Program</th><th class="text-end">Aksi</th></tr></thead><tbody>@forelse($types as $type)<tr><td><code>{{ $type->code }}</code></td><td><strong>{{ $type->name }}</strong></td><td>{{ $type->description ?: '-' }}</td><td><span class="badge text-bg-{{ $type->programs_count ? 'primary' : 'secondary' }}">{{ $type->programs_count }} data</span></td><td class="text-end"><button class="btn btn-sm btn-outline-primary" title="Edit" data-bs-toggle="modal" data-bs-target="#type{{ $type->id }}"><i class="fa fa-pen"></i></button>@if($type->programs_count)<button class="btn btn-sm btn-outline-secondary" title="Tidak dapat dihapus karena sudah digunakan" disabled><i class="fa fa-lock"></i></button>@else<form method="post" action="/console/program-mbbr/jenis/{{ $type->id }}" class="d-inline">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger js-swal-delete" data-message="Hapus jenis MBBR {{ $type->name }}?" title="Hapus"><i class="fa fa-trash"></i></button></form>@endif</td></tr>@empty<tr><td colspan="5" class="text-center text-secondary py-5">Belum ada jenis MBBR.</td></tr>@endforelse</tbody></table></div></div>
@include('console.mbbr.type-form',['id'=>'typeCreate','action'=>'/console/program-mbbr/jenis','type'=>null])
@foreach($types as $type)
    @include('console.mbbr.type-form',['id'=>'type'.$type->id,'action'=>'/console/program-mbbr/jenis/'.$type->id,'type'=>$type])
@endforeach
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
@include('console.end')
