@extends('frontend.layouts.public')

@section('content')
<style>
    .docs-page{padding:38px 0 72px;background:linear-gradient(180deg,#f2f9fa 0,#fff 68%)}.docs-head{max-width:780px;margin:0 auto 28px;text-align:center}.docs-head h1{margin:0;color:#193f54;font-size:2rem;font-weight:900}.docs-head p{margin:9px 0 0;color:#71838c}.docs-filter{display:flex;justify-content:center;gap:9px;flex-wrap:wrap;margin-bottom:26px}.docs-filter a{padding:9px 15px;border:1px solid #d4e4e8;border-radius:999px;background:#fff;color:#52717f;font-size:.8rem;font-weight:800;text-decoration:none}.docs-filter a.active,.docs-filter a:hover{border-color:#176eb1;background:#176eb1;color:#fff}.doc-list{overflow:hidden;border:1px solid #d7e7ea;border-radius:16px;background:#fff;box-shadow:0 12px 30px #173e5412}.doc-row{display:flex;align-items:center;gap:16px;padding:17px 19px;border-bottom:1px solid #e5eef0}.doc-row:last-child{border-bottom:0}.doc-icon{display:grid;flex:0 0 46px;width:46px;height:46px;place-items:center;border-radius:11px;background:#e8f4fa;color:#1976b6;font-size:1.25rem}.doc-info{min-width:0;flex:1}.doc-info h2{margin:0 0 4px;color:#284b5e;font-size:1rem;font-weight:900}.doc-info p{margin:0;color:#758b94;font-size:.79rem}.doc-meta{margin-top:6px;color:#98aab1;font-size:.7rem}.doc-download{flex:0 0 auto;border:1px solid #bcdde9;border-radius:9px;color:#176da9;font-size:.78rem;font-weight:800}.doc-download:hover{background:#176da9;color:#fff}.docs-empty{padding:50px 20px;color:#8399a3;text-align:center}.docs-empty i{display:block;margin-bottom:10px;font-size:2rem;color:#a9c1ca}@media(max-width:576px){.docs-head h1{font-size:1.6rem}.doc-row{align-items:flex-start;padding:14px}.doc-icon{flex-basis:38px;width:38px;height:38px}.doc-download{padding:7px}.doc-download span{display:none}}
</style>
@php($pageInfo=['peraturan'=>['PERATURAN','Dokumen peraturan dan ketentuan bidang perumahan serta kawasan permukiman.','fas fa-scale-balanced'],'informasi'=>['INFORMASI','Dokumen publikasi dan informasi layanan Dinas PKP Maluku.','fas fa-circle-info'],'unduhan'=>['PUSAT UNDUHAN','Seluruh dokumen publik yang tersedia untuk diunduh.','fas fa-download']][$documentPage])
<main class="docs-page"><div class="container"><header class="docs-head"><h1><i class="{{ $pageInfo[2] }} text-primary me-2"></i>{{ $pageInfo[0] }}</h1><p>{{ $pageInfo[1] }}</p></header><nav class="docs-filter"><a href="/peraturan" class="{{ $documentPage==='peraturan'?'active':'' }}"><i class="fas fa-scale-balanced me-1"></i>Peraturan</a><a href="/informasi" class="{{ $documentPage==='informasi'?'active':'' }}"><i class="fas fa-circle-info me-1"></i>Informasi</a><a href="/unduhan" class="{{ $documentPage==='unduhan'?'active':'' }}"><i class="fas fa-download me-1"></i>Semua Unduhan</a></nav><section class="doc-list">@forelse($documentList as $document)@php($fileUrl=str_starts_with($document->file_path,'assets/') ? asset($document->file_path) : asset('storage/'.$document->file_path))<article class="doc-row"><div class="doc-icon"><i class="{{ str_ends_with(strtolower($document->file_path), '.pdf') ? 'fas fa-file-pdf' : 'fas fa-file-alt' }}"></i></div><div class="doc-info"><h2>{{ $document->title }}</h2>@if($document->description)<p>{{ $document->description }}</p>@endif<div class="doc-meta"><i class="far fa-calendar-alt me-1"></i>{{ optional($document->published_date)->translatedFormat('d F Y') ?: 'Tanggal belum dicantumkan' }} &nbsp; <span class="badge text-bg-light text-secondary">{{ ucfirst($document->category) }}</span></div></div><a class="btn doc-download" href="{{ $fileUrl }}" target="_blank" download><i class="fas fa-download me-1"></i><span>Unduh</span></a></article>@empty<div class="docs-empty"><i class="fas fa-folder-open"></i>Belum ada dokumen yang tersedia.</div>@endforelse</section></div></main>
@endsection
