<?php

use App\Http\Controllers\ConsoleController;
use App\Http\Controllers\FrontendController;
use App\Http\Controllers\ProvincialLeaderController;
use App\Http\Controllers\WelcomeSlideController;
use App\Http\Controllers\StructuralOfficialController;
use App\Http\Controllers\MbbrRecipientController;
use App\Http\Controllers\GalleryController;
use App\Http\Controllers\DocumentController;
use App\Http\Controllers\WebManagementController;
use App\Http\Controllers\MbbrManagementController;
use App\Http\Controllers\NewsController;
use App\Http\Controllers\AgendaController;
use App\Http\Controllers\ServiceReviewController;
use App\Http\Controllers\PkpServiceController;
use App\Http\Controllers\RlthRecordController;
use App\Http\Controllers\ProposalDataController;
use App\Http\Controllers\PublicRlthSubmissionController;
use Illuminate\Support\Facades\Route;

Route::get('/', [FrontendController::class, 'page']);
Route::post('/ulasan', [FrontendController::class, 'storeReview'])->name('reviews.store');
Route::get('/geomap-data', [FrontendController::class, 'mapData'])->name('geomap.data');
Route::get('/berita/{slug}', [FrontendController::class, 'newsDetail'])->where('slug', '[a-z0-9-]+');
Route::get('/form-pendataan-rtlh', [PublicRlthSubmissionController::class, 'create'])->name('public.rlth.create');
Route::post('/form-pendataan-rtlh', [PublicRlthSubmissionController::class, 'store'])->name('public.rlth.store');
Route::get('/{page}', [FrontendController::class, 'page'])->whereIn('page', ['profil-dinas','visi-misi','tugas-pokok-fungsi','struktur-organisasi','profil-pejabat','agenda-kegiatan','program-kegiatan','layanan-pkp','pendataan-rlth','data-usulan','sadata-kp','sadata-psu','kawasan-kumuh','berita','geomap','galeri','peraturan','informasi','unduhan','kontak']);
Route::get('/console/login', [ConsoleController::class, 'login']);
Route::post('/console/login', [ConsoleController::class, 'auth']);
Route::post('/console/logout', [ConsoleController::class, 'logout']);
Route::middleware('console.auth')->prefix('console')->group(function () {
    Route::get('/layanan-pkp', [PkpServiceController::class, 'index']);
    Route::post('/layanan-pkp', [PkpServiceController::class, 'store']);
    Route::put('/layanan-pkp/{service}', [PkpServiceController::class, 'update']);
    Route::delete('/layanan-pkp/{service}', [PkpServiceController::class, 'destroy']);
    Route::get('/pendataan-rlth', [RlthRecordController::class, 'index']);
    Route::get('/pendataan-rlth/template', [RlthRecordController::class, 'template']);
    Route::post('/pendataan-rlth', [RlthRecordController::class, 'store']);
    Route::post('/pendataan-rlth/import', [RlthRecordController::class, 'import']);
    Route::patch('/pendataan-rlth/{record}/status', [RlthRecordController::class, 'updateStatus']);
    Route::put('/pendataan-rlth/{record}', [RlthRecordController::class, 'update']);
    Route::delete('/pendataan-rlth/{record}', [RlthRecordController::class, 'destroy']);
    Route::get('/data-usulan', [ProposalDataController::class, 'index']);
    Route::post('/data-usulan', [ProposalDataController::class, 'store']);
    Route::put('/data-usulan/{proposal}', [ProposalDataController::class, 'update']);
    Route::delete('/data-usulan/{proposal}', [ProposalDataController::class, 'destroy']);
    Route::get('/ulasan-layanan', [ServiceReviewController::class, 'index']);
    Route::delete('/ulasan-layanan/{review}', [ServiceReviewController::class, 'destroy']);
    Route::get('/agenda', [AgendaController::class, 'index']);
    Route::post('/agenda', [AgendaController::class, 'store']);
    Route::put('/agenda/{agenda}', [AgendaController::class, 'update']);
    Route::delete('/agenda/{agenda}', [AgendaController::class, 'destroy']);
    Route::get('/berita', [NewsController::class, 'index']);
    Route::post('/berita', [NewsController::class, 'store']);
    Route::put('/berita/{post}', [NewsController::class, 'update']);
    Route::delete('/berita/{post}', [NewsController::class, 'destroy']);
    Route::get('/kelola-web', [WebManagementController::class, 'index']);
    Route::get('/kelola-web/pengaturan-website', [WebManagementController::class, 'settings']);
    Route::put('/kelola-web/pengaturan-website', [WebManagementController::class, 'updateSettings']);
    Route::get('/kelola-web/{section}', [WebManagementController::class, 'page'])->whereIn('section', ['profil-dinas','visi-misi','tugas-fungsi','struktur-organisasi']);
    Route::put('/kelola-web/{section}', [WebManagementController::class, 'save'])->whereIn('section', ['profil-dinas','visi-misi','tugas-fungsi']);
    Route::post('/kelola-web/struktur-organisasi', [WebManagementController::class, 'storeUnit']);
    Route::put('/kelola-web/struktur-organisasi/{unit}', [WebManagementController::class, 'updateUnit']);
    Route::delete('/kelola-web/struktur-organisasi/{unit}', [WebManagementController::class, 'destroyUnit']);
    Route::get('/program-mbbr', [MbbrManagementController::class, 'dashboard']);
    Route::post('/program-mbbr/sub-program', [MbbrManagementController::class, 'storeProgram']);
    Route::get('/program-mbbr/sub-program', [MbbrManagementController::class, 'programs']);
    Route::put('/program-mbbr/sub-program/{program}', [MbbrManagementController::class, 'updateProgram']);
    Route::delete('/program-mbbr/sub-program/{program}', [MbbrManagementController::class, 'destroyProgram']);
    Route::get('/program-mbbr/jenis', [MbbrManagementController::class, 'types']);
    Route::post('/program-mbbr/jenis', [MbbrManagementController::class, 'storeType']);
    Route::put('/program-mbbr/jenis/{type}', [MbbrManagementController::class, 'updateType']);
    Route::delete('/program-mbbr/jenis/{type}', [MbbrManagementController::class, 'destroyType']);
    Route::get('/program-mbbr/import-penerima', [MbbrManagementController::class, 'importPage']);
    Route::post('/program-mbbr/import-penerima', [MbbrManagementController::class, 'import']);
    Route::get('/program-mbbr/geojson-wilayah', [MbbrManagementController::class, 'areas']);
    Route::post('/program-mbbr/geojson-wilayah', [MbbrManagementController::class, 'storeArea']);
    Route::post('/program-mbbr/geojson-wilayah/import', [MbbrManagementController::class, 'importAreas']);
    Route::put('/program-mbbr/geojson-wilayah/{area}', [MbbrManagementController::class, 'updateArea']);
    Route::delete('/program-mbbr/geojson-wilayah/{area}', [MbbrManagementController::class, 'destroyArea']);
    Route::get('/program-mbbr/data-penerima', fn () => redirect('/console/penerima'));
    Route::get('/program-mbbr/data-desa', [MbbrManagementController::class, 'villages']);
    Route::post('/program-mbbr/data-desa', [MbbrManagementController::class, 'storeVillage']);
    Route::put('/program-mbbr/data-desa/{village}', [MbbrManagementController::class, 'updateVillage']);
    Route::delete('/program-mbbr/data-desa/{village}', [MbbrManagementController::class, 'destroyVillage']);
    Route::get('/galeri', [GalleryController::class, 'index']);
    Route::post('/galeri', [GalleryController::class, 'store']);
    Route::put('/galeri/{gallery}', [GalleryController::class, 'update']);
    Route::delete('/galeri/{gallery}', [GalleryController::class, 'destroy']);
    Route::get('/dokumen', [DocumentController::class, 'index']);
    Route::post('/dokumen', [DocumentController::class, 'store']);
    Route::put('/dokumen/{document}', [DocumentController::class, 'update']);
    Route::delete('/dokumen/{document}', [DocumentController::class, 'destroy']);
    Route::get('/penerima', [MbbrRecipientController::class, 'index']);
    Route::get('/penerima/export', [MbbrRecipientController::class, 'export']);
    Route::post('/penerima', [MbbrRecipientController::class, 'store']);
    Route::put('/penerima/{recipient}', [MbbrRecipientController::class, 'update']);
    Route::delete('/penerima/{recipient}', [MbbrRecipientController::class, 'destroy']);
    Route::put('/penerima/{recipient}/foto', [MbbrRecipientController::class, 'updatePhotos']);
    Route::get('/pimpinan', [ProvincialLeaderController::class,'index']);
    Route::post('/pimpinan', [ProvincialLeaderController::class,'store']);
    Route::put('/pimpinan/{leader}', [ProvincialLeaderController::class,'update']);
    Route::delete('/pimpinan/{leader}', [ProvincialLeaderController::class,'destroy']);
    Route::get('/slider-sambutan', [WelcomeSlideController::class,'index']);
    Route::post('/slider-sambutan', [WelcomeSlideController::class,'store']);
    Route::put('/slider-sambutan/{slide}', [WelcomeSlideController::class,'update']);
    Route::delete('/slider-sambutan/{slide}', [WelcomeSlideController::class,'destroy']);
    Route::get('/pejabat', [StructuralOfficialController::class,'index']);
    Route::post('/pejabat', [StructuralOfficialController::class,'store']);
    Route::put('/pejabat/{official}', [StructuralOfficialController::class,'update']);
    Route::delete('/pejabat/{official}', [StructuralOfficialController::class,'destroy']);
    Route::get('/', [ConsoleController::class, 'dashboard']);
    Route::get('/users', [ConsoleController::class, 'users']);
    Route::get('/{module}', [ConsoleController::class, 'module'])->whereIn('module', ['users','agenda']);
    Route::post('/{module}', [ConsoleController::class, 'store'])->whereIn('module', ['users','agenda']);
    Route::put('/{module}/{id}', [ConsoleController::class, 'update'])->whereIn('module', ['users','agenda']);
    Route::delete('/{module}/{id}', [ConsoleController::class, 'destroy'])->whereIn('module', ['users','agenda']);
});
