@php($statuses = ['submitted' => 'Diajukan', 'verified' => 'Terverifikasi', 'approved' => 'Disetujui', 'rejected' => 'Ditolak'])

@once
<style>
    .proposal-entry-modal{border:0;border-radius:20px;overflow:hidden}.proposal-entry-modal .modal-header{padding:20px 24px;border:0;background:linear-gradient(135deg,#174b68,#287b9f);color:#fff}.proposal-entry-modal .modal-header h2{margin:0;color:#fff;font-size:1.12rem;font-weight:800}.proposal-entry-modal .btn-close{filter:invert(1)}.proposal-entry-modal .modal-body{padding:24px;background:#f6fafb}.proposal-entry-modal .modal-footer{padding:16px 24px;border:0;background:#fff}.proposal-intro{display:flex;align-items:flex-start;gap:12px;margin-bottom:20px;padding:14px 16px;border:1px solid #d7e9ef;border-radius:13px;background:#edf7fa;color:#507080;font-size:.82rem}.proposal-intro i{margin-top:2px;color:#19759c}.proposal-section{padding:20px;margin-bottom:16px;border:1px solid #e0ebef;border-radius:16px;background:#fff;box-shadow:0 7px 20px rgba(19,65,83,.045)}.proposal-section-title{display:flex;align-items:center;gap:9px;margin:0 0 18px;color:#17465e;font-size:.94rem;font-weight:800}.proposal-section-title .section-number{display:grid;width:28px;height:28px;place-items:center;border-radius:8px;background:#e5f3f8;color:#18769c;font-size:.75rem}.proposal-entry-modal .form-label{margin-bottom:6px}.proposal-entry-modal .form-control,.proposal-entry-modal .form-select{min-height:42px;background:#fcfefe}.proposal-entry-modal textarea.form-control{min-height:auto}.proposal-doc-field{padding:12px;border:1px dashed #cfdee4;border-radius:11px;background:#fbfdfd}.proposal-doc-field .form-label{color:#315d70}@media(max-width:576px){.proposal-entry-modal .modal-body{padding:15px}.proposal-section{padding:15px}.proposal-entry-modal .modal-header,.proposal-entry-modal .modal-footer{padding:16px}}
</style>
@endonce

<div class="modal fade" id="{{ $id }}" tabindex="-1"><div class="modal-dialog modal-xl modal-dialog-scrollable"><form method="post" action="{{ $action }}" class="modal-content proposal-entry-modal">@csrf @if($proposal) @method('PUT') @endif
    <div class="modal-header"><div><h2><i class="fa fa-file-circle-plus me-2"></i>{{ $proposal ? 'Edit' : 'Tambah' }} Data Usulan</h2><small class="opacity-75">Catat usulan perumahan secara terukur dan terdokumentasi.</small></div><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div>
    <div class="modal-body"><div class="proposal-intro"><i class="fa fa-circle-info"></i><span>Kolom bertanda <span class="text-danger">*</span> wajib diisi. Lengkapi lokasi dan dokumen pendukung agar proses verifikasi lebih mudah.</span></div>
        <section class="proposal-section"><h3 class="proposal-section-title"><span class="section-number">01</span>Administrasi Usulan</h3><div class="row g-3">
            <div class="col-sm-4 col-md-2"><label class="form-label">Tahun <span class="text-danger">*</span></label><input name="proposal_year" type="number" min="2000" max="2100" value="{{ $proposal?->proposal_year ?? now()->year }}" class="form-control" required></div><div class="col-sm-4 col-md-2"><label class="form-label">No. Sumber</label><input name="source_number" type="number" min="1" value="{{ $proposal?->source_number }}" class="form-control"></div><div class="col-sm-4 col-md-3"><label class="form-label">Sumber Data <span class="text-danger">*</span></label><select name="data_source" class="form-select" required><option value="">Pilih sumber</option><option value="provinsi" @selected($proposal?->data_source==='provinsi')>Provinsi</option><option value="kab_kota" @selected($proposal?->data_source==='kab_kota')>Kab/Kota</option><option value="masyarakat" @selected($proposal?->data_source==='masyarakat')>Masyarakat</option></select></div><div class="col-md-3"><label class="form-label">Nomor Usulan</label><input name="proposal_number" value="{{ $proposal?->proposal_number }}" class="form-control" placeholder="Nomor surat/registrasi"></div><div class="col-md-2"><label class="form-label">Status <span class="text-danger">*</span></label><select name="status" class="form-select" required>@foreach($statuses as $value=>$label)<option value="{{ $value }}" @selected(($proposal?->status ?? 'submitted') === $value)>{{ $label }}</option>@endforeach</select></div>
        </div></section>
        <section class="proposal-section"><h3 class="proposal-section-title"><span class="section-number">02</span>Data Pengusul</h3><div class="row g-3">
            <div class="col-md-6"><label class="form-label">Nama Pengusul <span class="text-danger">*</span></label><input name="applicant_name" value="{{ $proposal?->applicant_name }}" class="form-control" required></div><div class="col-md-3"><label class="form-label">NIK</label><input name="national_id" value="{{ $proposal?->national_id }}" class="form-control" inputmode="numeric" placeholder="16 digit NIK"></div><div class="col-md-3"><label class="form-label">Nomor KK</label><input name="family_card_number" value="{{ $proposal?->family_card_number }}" class="form-control" inputmode="numeric" placeholder="16 digit nomor KK"></div><div class="col-md-3"><label class="form-label">DTSEN Backlog</label><input name="dtsen_backlog" value="{{ $proposal?->dtsen_backlog }}" class="form-control"></div><div class="col-md-3"><label class="form-label">DTSEN Desil</label><input name="dtsen_decile" value="{{ $proposal?->dtsen_decile }}" class="form-control"></div><div class="col-md-3"><label class="form-label">Nomor HP</label><input name="applicant_phone" value="{{ $proposal?->applicant_phone }}" class="form-control" inputmode="tel" placeholder="Contoh: 0812xxxx"></div><div class="col-md-3"><label class="form-label">Kepemilikan Lahan</label><input name="land_ownership_type" value="{{ $proposal?->land_ownership_type }}" class="form-control" placeholder="Contoh: SHM"></div>
        </div></section>
        <section class="proposal-section"><h3 class="proposal-section-title"><span class="section-number">03</span>Lokasi dan Rincian Usulan</h3><div class="row g-3">
            <div class="col-md-3"><label class="form-label">Provinsi</label><input name="province_name" value="{{ $proposal?->province_name ?? 'MALUKU' }}" class="form-control"></div><div class="col-md-3"><label class="form-label">Kabupaten/Kota</label><input name="regency_name" value="{{ $proposal?->regency_name }}" class="form-control"></div><div class="col-md-3"><label class="form-label">Kecamatan</label><input name="district_name" value="{{ $proposal?->district_name }}" class="form-control"></div><div class="col-md-3"><label class="form-label">Desa/Kelurahan</label><input name="village_name" value="{{ $proposal?->village_name }}" class="form-control"></div><div class="col-md-6"><label class="form-label">Alamat Lengkap</label><input name="address" value="{{ $proposal?->address }}" class="form-control"></div><div class="col-md-3"><label class="form-label">Latitude</label><input name="latitude" type="number" step="0.0000001" value="{{ $proposal?->latitude }}" class="form-control" placeholder="Contoh: -3.654321"></div><div class="col-md-3"><label class="form-label">Longitude</label><input name="longitude" type="number" step="0.0000001" value="{{ $proposal?->longitude }}" class="form-control" placeholder="Contoh: 128.123456"></div><div class="col-md-4"><label class="form-label">Kategori Usulan</label><input name="proposal_category" value="{{ $proposal?->proposal_category }}" class="form-control"></div><div class="col-md-4"><label class="form-label">Jenis Usulan</label><input name="proposal_type" value="{{ $proposal?->proposal_type }}" class="form-control"></div><div class="col-md-2"><label class="form-label">Penerima Manfaat</label><input name="beneficiary_count" type="number" min="0" value="{{ $proposal?->beneficiary_count }}" class="form-control"></div><div class="col-md-2"><label class="form-label">Estimasi Anggaran</label><input name="estimated_budget" type="number" min="0" value="{{ $proposal?->estimated_budget }}" class="form-control"></div><div class="col-12"><label class="form-label">Uraian Usulan</label><textarea name="description" class="form-control" rows="3" placeholder="Jelaskan kebutuhan atau usulan pembangunan.">{{ $proposal?->description }}</textarea></div><div class="col-12"><label class="form-label">Catatan Verifikasi</label><textarea name="verification_notes" class="form-control" rows="2" placeholder="Diisi saat proses verifikasi.">{{ $proposal?->verification_notes }}</textarea></div>
        </div></section>
        <section class="proposal-section mb-0"><h3 class="proposal-section-title"><span class="section-number">04</span>Tautan Berkas dan Dokumentasi</h3><div class="row g-3">@foreach(['ktp_file_url'=>'Link Berkas KTP','kk_file_url'=>'Link Berkas KK','certificate_file_url'=>'Link Berkas Sertipikat','photo_front_url'=>'Link Foto Depan','photo_back_url'=>'Link Foto Belakang','photo_left_url'=>'Link Foto Kiri','photo_right_url'=>'Link Foto Kanan','photo_inside_url'=>'Link Foto Dalam'] as $field=>$label)<div class="col-md-6"><div class="proposal-doc-field"><label class="form-label">{{ $label }}</label><input name="{{ $field }}" type="url" value="{{ $proposal?->{$field} }}" class="form-control" placeholder="https://..."></div></div>@endforeach</div></section>
    </div><div class="modal-footer"><button type="button" class="btn btn-light border" data-bs-dismiss="modal">Batal</button><button class="btn btn-primary px-4"><i class="fa fa-floppy-disk me-1"></i>Simpan Data</button></div>
</form></div></div>
