@php($statuses = ['submitted' => 'Diajukan', 'verified' => 'Terverifikasi', 'approved' => 'Disetujui', 'rejected' => 'Ditolak'])
<div class="modal fade" id="{{ $id }}" tabindex="-1"><div class="modal-dialog modal-xl modal-dialog-scrollable"><form method="post" action="{{ $action }}" class="modal-content">@csrf @if($proposal) @method('PUT') @endif
    <div class="modal-header"><h2 class="fs-5"><i class="fa fa-file-circle-plus me-2"></i>{{ $proposal ? 'Edit' : 'Tambah' }} Data Usulan</h2><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div>
    <div class="modal-body">
        <h3 class="h6 text-primary border-bottom pb-2">Identitas Usulan</h3><div class="row g-3 mb-4">
            <div class="col-md-2"><label class="form-label">Tahun</label><input name="proposal_year" type="number" min="2000" max="2100" value="{{ $proposal?->proposal_year ?? now()->year }}" class="form-control" required></div>
            <div class="col-md-2"><label class="form-label">No. Sumber</label><input name="source_number" type="number" min="1" value="{{ $proposal?->source_number }}" class="form-control"></div>
            <div class="col-md-4"><label class="form-label">Nomor Usulan</label><input name="proposal_number" value="{{ $proposal?->proposal_number }}" class="form-control"></div>
            <div class="col-md-4"><label class="form-label">Status</label><select name="status" class="form-select" required>@foreach($statuses as $value=>$label)<option value="{{ $value }}" @selected(($proposal?->status ?? 'submitted') === $value)>{{ $label }}</option>@endforeach</select></div>
            <div class="col-md-6"><label class="form-label">Nama Pengusul</label><input name="applicant_name" value="{{ $proposal?->applicant_name }}" class="form-control" required></div><div class="col-md-3"><label class="form-label">NIK</label><input name="national_id" value="{{ $proposal?->national_id }}" class="form-control"></div><div class="col-md-3"><label class="form-label">Nomor KK</label><input name="family_card_number" value="{{ $proposal?->family_card_number }}" class="form-control"></div>
            <div class="col-md-3"><label class="form-label">DTSEN Backlog</label><input name="dtsen_backlog" value="{{ $proposal?->dtsen_backlog }}" class="form-control"></div><div class="col-md-3"><label class="form-label">DTSEN Desil</label><input name="dtsen_decile" value="{{ $proposal?->dtsen_decile }}" class="form-control"></div><div class="col-md-3"><label class="form-label">Nomor HP</label><input name="applicant_phone" value="{{ $proposal?->applicant_phone }}" class="form-control"></div><div class="col-md-3"><label class="form-label">Kepemilikan Lahan</label><input name="land_ownership_type" value="{{ $proposal?->land_ownership_type }}" class="form-control" placeholder="Contoh: SHM"></div>
        </div>
        <h3 class="h6 text-primary border-bottom pb-2">Wilayah dan Detail</h3><div class="row g-3 mb-4"><div class="col-md-3"><label class="form-label">Provinsi</label><input name="province_name" value="{{ $proposal?->province_name ?? 'MALUKU' }}" class="form-control"></div><div class="col-md-3"><label class="form-label">Kabupaten/Kota</label><input name="regency_name" value="{{ $proposal?->regency_name }}" class="form-control"></div><div class="col-md-3"><label class="form-label">Kecamatan</label><input name="district_name" value="{{ $proposal?->district_name }}" class="form-control"></div><div class="col-md-3"><label class="form-label">Desa/Kelurahan</label><input name="village_name" value="{{ $proposal?->village_name }}" class="form-control"></div><div class="col-md-6"><label class="form-label">Alamat Lengkap</label><input name="address" value="{{ $proposal?->address }}" class="form-control"></div><div class="col-md-3"><label class="form-label">Latitude</label><input name="latitude" type="number" step="0.0000001" value="{{ $proposal?->latitude }}" class="form-control"></div><div class="col-md-3"><label class="form-label">Longitude</label><input name="longitude" type="number" step="0.0000001" value="{{ $proposal?->longitude }}" class="form-control"></div><div class="col-md-4"><label class="form-label">Kategori Usulan</label><input name="proposal_category" value="{{ $proposal?->proposal_category }}" class="form-control"></div><div class="col-md-4"><label class="form-label">Jenis Usulan</label><input name="proposal_type" value="{{ $proposal?->proposal_type }}" class="form-control"></div><div class="col-md-2"><label class="form-label">Penerima Manfaat</label><input name="beneficiary_count" type="number" min="0" value="{{ $proposal?->beneficiary_count }}" class="form-control"></div><div class="col-md-2"><label class="form-label">Estimasi Anggaran</label><input name="estimated_budget" type="number" min="0" value="{{ $proposal?->estimated_budget }}" class="form-control"></div><div class="col-12"><label class="form-label">Uraian Usulan</label><textarea name="description" class="form-control" rows="2">{{ $proposal?->description }}</textarea></div><div class="col-12"><label class="form-label">Catatan Verifikasi</label><textarea name="verification_notes" class="form-control" rows="2">{{ $proposal?->verification_notes }}</textarea></div></div>
        <h3 class="h6 text-primary border-bottom pb-2">Tautan Berkas dan Dokumentasi</h3><div class="row g-3">@foreach(['ktp_file_url'=>'Link Berkas KTP','kk_file_url'=>'Link Berkas KK','certificate_file_url'=>'Link Berkas Sertipikat','photo_front_url'=>'Link Foto Depan','photo_back_url'=>'Link Foto Belakang','photo_left_url'=>'Link Foto Kiri','photo_right_url'=>'Link Foto Kanan','photo_inside_url'=>'Link Foto Dalam'] as $field=>$label)<div class="col-md-6"><label class="form-label">{{ $label }}</label><input name="{{ $field }}" type="url" value="{{ $proposal?->{$field} }}" class="form-control" placeholder="https://..."></div>@endforeach</div>
    </div><div class="modal-footer"><button type="button" class="btn btn-light" data-bs-dismiss="modal">Batal</button><button class="btn btn-primary"><i class="fa fa-floppy-disk me-1"></i>Simpan Data</button></div>
</form></div></div>
