@include('console.nav', ['title' => 'Data Usulan'])
<div class="d-flex flex-wrap justify-content-between align-items-center gap-3 mb-4"><p class="text-secondary mb-0">Kelola rekap usulan BSPS Nasional dan data pendukungnya.</p><button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#proposalCreate"><i class="fa fa-plus me-1"></i>Tambah Usulan</button></div>
<div class="row g-3 mb-4"><div class="col-md-6"><div class="card p-3"><small class="text-secondary">Total Usulan</small><strong class="fs-3">{{ number_format($total) }}</strong></div></div><div class="col-md-6"><div class="card p-3"><small class="text-secondary">Terverifikasi</small><strong class="fs-3 text-success">{{ number_format($verified) }}</strong></div></div></div>
<form class="card p-3 mb-4"><div class="row g-3 align-items-end"><div class="col-md-4"><label class="form-label">Cari</label><input name="cari" class="form-control" value="{{ request('cari') }}" placeholder="Nama, NIK, atau desa"></div><div class="col-md-2"><label class="form-label">Tahun</label><select name="tahun" class="form-select"><option value="">Semua</option>@foreach($years as $year)<option value="{{ $year }}" @selected(request('tahun')==$year)>{{ $year }}</option>@endforeach</select></div><div class="col-md-3"><label class="form-label">Kabupaten/Kota</label><select name="kabupaten" class="form-select"><option value="">Semua</option>@foreach($regencies as $regency)<option value="{{ $regency }}" @selected(request('kabupaten')===$regency)>{{ $regency }}</option>@endforeach</select></div><div class="col-md-3"><label class="form-label">Status</label><select name="status" class="form-select"><option value="">Semua</option>@foreach(['submitted'=>'Diajukan','verified'=>'Terverifikasi','approved'=>'Disetujui','rejected'=>'Ditolak'] as $value=>$label)<option value="{{ $value }}" @selected(request('status')===$value)>{{ $label }}</option>@endforeach</select></div><div class="col-12"><button class="btn btn-primary"><i class="fa fa-filter me-1"></i>Filter</button><a href="/console/data-usulan" class="btn btn-light">Reset</a></div></div></form>
<div class="card overflow-hidden"><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Pengusul</th><th>Wilayah</th><th>DTSEN</th><th>Kepemilikan</th><th>Status</th><th>Dokumen</th><th class="text-end">Aksi</th></tr></thead><tbody>@forelse($proposals as $proposal)<tr><td><strong>{{ $proposal->applicant_name }}</strong><br><small class="text-secondary">{{ $proposal->proposal_year }} · {{ $proposal->national_id ? 'NIK: '.substr($proposal->national_id,-4) : '-' }}</small></td><td>{{ $proposal->regency_name ?: '-' }}<br><small>{{ $proposal->district_name ?: '-' }}, {{ $proposal->village_name ?: '-' }}</small></td><td>{{ $proposal->dtsen_backlog ?: '-' }} / {{ $proposal->dtsen_decile ?: '-' }}</td><td>{{ $proposal->land_ownership_type ?: '-' }}</td><td><span class="badge text-bg-{{ ['submitted'=>'secondary','verified'=>'success','approved'=>'primary','rejected'=>'danger'][$proposal->status] }}">{{ ['submitted'=>'Diajukan','verified'=>'Terverifikasi','approved'=>'Disetujui','rejected'=>'Ditolak'][$proposal->status] }}</span></td><td>@if($proposal->ktp_file_url || $proposal->photo_front_url)<span class="badge text-bg-success">Ada</span>@else<span class="badge text-bg-light">-</span>@endif</td><td class="text-end"><button class="btn btn-sm btn-outline-primary" data-bs-toggle="modal" data-bs-target="#proposal{{ $proposal->id }}"><i class="fa fa-pen"></i></button><form action="/console/data-usulan/{{ $proposal->id }}" method="post" class="d-inline">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger js-swal-delete" data-message="Hapus usulan {{ $proposal->applicant_name }}?"><i class="fa fa-trash"></i></button></form></td></tr>@empty<tr><td colspan="7" class="text-center text-secondary py-5">Belum ada data usulan.</td></tr>@endforelse</tbody></table></div>@if($proposals->hasPages())<div class="p-3 border-top">{{ $proposals->links() }}</div>@endif</div>
@include('console.proposal-data.form', ['id'=>'proposalCreate','action'=>'/console/data-usulan','proposal'=>null])
@foreach($proposals as $proposal)@include('console.proposal-data.form', ['id'=>'proposal'.$proposal->id,'action'=>'/console/data-usulan/'.$proposal->id,'proposal'=>$proposal])@endforeach
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
@include('console.end')
