<?php
use Illuminate\Database\Migrations\Migration; use Illuminate\Database\Schema\Blueprint; use Illuminate\Support\Facades\Schema;
return new class extends Migration { public function up(): void {
Schema::create('users', function(Blueprint $t){$t->id();$t->string('name');$t->string('username')->unique();$t->string('email')->nullable()->unique();$t->string('password');$t->enum('role',['admin','editor'])->default('editor');$t->boolean('is_active')->default(true);$t->rememberToken();$t->timestamps();});
Schema::create('website_settings', function(Blueprint $t){$t->id();$t->string('agency_name');$t->string('short_name')->nullable();$t->text('about')->nullable();$t->text('vision')->nullable();$t->text('mission')->nullable();$t->text('duties')->nullable();$t->text('address')->nullable();$t->string('phone')->nullable();$t->string('email')->nullable();$t->string('website')->nullable();$t->json('social_links')->nullable();$t->timestamps();});
Schema::create('posts', function(Blueprint $t){$t->id();$t->string('title');$t->string('slug')->unique();$t->text('excerpt')->nullable();$t->longText('content');$t->string('cover_image')->nullable();$t->enum('status',['draft','published'])->default('draft');$t->timestamp('published_at')->nullable();$t->foreignId('author_id')->nullable()->constrained('users')->nullOnDelete();$t->timestamps();});
Schema::create('galleries', function(Blueprint $t){$t->id();$t->string('title');$t->text('description')->nullable();$t->string('image_path')->nullable();$t->string('video_url')->nullable();$t->enum('category',['kegiatan','informasi','video'])->default('kegiatan');$t->boolean('is_active')->default(true);$t->timestamps();});
Schema::create('documents', function(Blueprint $t){$t->id();$t->string('title');$t->enum('category',['peraturan','informasi','unduhan']);$t->string('file_path');$t->text('description')->nullable();$t->date('published_date')->nullable();$t->timestamps();});
Schema::create('structural_officials', function(Blueprint $t){$t->id();$t->string('name');$t->string('position');$t->string('echelon')->nullable();$t->string('photo_path')->nullable();$t->text('bio')->nullable();$t->unsignedInteger('sort_order')->default(0);$t->boolean('is_active')->default(true);$t->timestamps();});
Schema::create('regencies', function(Blueprint $t){$t->id();$t->string('name')->unique();$t->timestamps();});
Schema::create('villages', function(Blueprint $t){$t->id();$t->foreignId('regency_id')->constrained()->cascadeOnDelete();$t->string('name');$t->timestamps();$t->unique(['regency_id','name']);});
Schema::create('mbbr_program_types', function(Blueprint $t){$t->id();$t->string('code')->unique();$t->string('name');$t->text('description')->nullable();$t->string('color',20)->default('#0d6efd');$t->timestamps();});
Schema::create('mbbr_programs', function(Blueprint $t){$t->id();$t->foreignId('mbbr_program_type_id')->nullable()->constrained()->nullOnDelete();$t->string('code')->unique();$t->string('name');$t->year('fiscal_year');$t->decimal('budget',18,2)->default(0);$t->enum('status',['planning','active','completed','cancelled'])->default('planning');$t->text('description')->nullable();$t->timestamps();});
Schema::create('mbbr_recipients', function(Blueprint $t){$t->id();$t->foreignId('mbbr_program_id')->constrained()->cascadeOnDelete();$t->foreignId('regency_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('village_id')->nullable()->constrained()->nullOnDelete();$t->string('name');$t->text('address')->nullable();$t->string('companion_name')->nullable();$t->decimal('latitude',10,7)->nullable();$t->decimal('longitude',10,7)->nullable();$t->decimal('progress',5,2)->default(0);$t->enum('status',['waiting','process','completed'])->default('waiting');$t->timestamps();});
Schema::create('mbbr_areas', function(Blueprint $t){$t->id();$t->foreignId('mbbr_program_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('regency_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('village_id')->nullable()->constrained()->nullOnDelete();$t->string('name');$t->json('geojson');$t->timestamps();});
Schema::create('agendas', function(Blueprint $t){$t->id();$t->string('title');$t->text('description')->nullable();$t->string('location')->nullable();$t->date('start_date');$t->date('end_date')->nullable();$t->time('start_time')->nullable();$t->time('end_time')->nullable();$t->enum('status',['draft','scheduled','ongoing','completed','cancelled'])->default('draft');$t->timestamps();});
Schema::create('service_reviews', function(Blueprint $t){$t->id();$t->string('name',100);$t->unsignedTinyInteger('rating');$t->timestamps();});
Schema::create('visitor_sessions', function(Blueprint $t){$t->id();$t->date('visit_date');$t->string('session_hash',64);$t->timestamps();$t->unique(['visit_date','session_hash']);});
} public function down(): void { Schema::dropIfExists('visitor_sessions');Schema::dropIfExists('service_reviews');Schema::dropIfExists('agendas');Schema::dropIfExists('mbbr_areas');Schema::dropIfExists('mbbr_recipients');Schema::dropIfExists('mbbr_programs');Schema::dropIfExists('mbbr_program_types');Schema::dropIfExists('villages');Schema::dropIfExists('regencies');Schema::dropIfExists('structural_officials');Schema::dropIfExists('documents');Schema::dropIfExists('galleries');Schema::dropIfExists('posts');Schema::dropIfExists('website_settings');Schema::dropIfExists('users'); }};
