@extends('frontend.layouts.public')

@section('content')
<main class="service-page py-5">
    <div class="container">
        <section class="service-hero mb-4">
            <div>
                <span class="service-kicker"><i class="fas fa-handshake-angle"></i> LAYANAN PUBLIK</span>
                <h1>Layanan Perumahan dan Kawasan Permukiman</h1>
                <p>Akses informasi dan layanan Dinas PKP Maluku untuk mendukung hunian layak serta kawasan permukiman yang berkualitas.</p>
            </div>
            <i class="fas fa-house-chimney service-hero-icon"></i>
        </section>
        <section class="mb-5"><div class="service-section-heading"><div><h2>Daftar Layanan PKP</h2><p>Pilih layanan untuk melanjutkan ke formulir atau tautan layanan yang tersedia.</p></div></div><div class="row g-4">@forelse($pkpServices as $service)<div class="col-md-6 col-lg-4"><a class="service-link-card" href="{{ $service->url }}" target="_blank" rel="noopener noreferrer"><i class="fas {{ $service->icon }}"></i><h2>{{ $service->title }}</h2><p>{{ $service->description ?: 'Klik untuk membuka layanan.' }}</p><span>Buka layanan <i class="fas fa-arrow-up-right-from-square ms-1"></i></span></a></div>@empty<div class="col-12"><div class="service-empty"><i class="fas fa-link"></i><h2>Layanan belum tersedia</h2><p>Admin dapat menambahkan tautan Google Form atau layanan lainnya melalui Console.</p></div></div>@endforelse</div></section>
        <section class="service-programs mt-5"><h2>Program PKP Tersedia</h2><div class="row g-3">@forelse($activeProgramTypes as $type)<div class="col-md-4"><article><i class="fas fa-layer-group"></i><div><strong>{{ $type->name }}</strong><small>{{ $type->programs_count }} program tersedia</small></div></article></div>@empty<div class="col-12"><p class="text-secondary mb-0">Data program belum tersedia.</p></div>@endforelse</div></section>
    </div>
</main>
<style>.service-page{background:#f6fafc}.service-hero{position:relative;overflow:hidden;display:flex;align-items:center;justify-content:space-between;gap:24px;padding:40px 48px;border-radius:24px;background:linear-gradient(135deg,#12445e,#1c7685);color:#fff;box-shadow:0 18px 38px #0b384428}.service-kicker{display:inline-flex;gap:8px;align-items:center;font-size:.78rem;font-weight:800;letter-spacing:.12em;color:#f3d89f}.service-hero h1{max-width:760px;margin:12px 0;font-size:clamp(1.75rem,3vw,2.6rem);font-weight:800}.service-hero p{max-width:720px;margin:0;color:#e5f4f5;font-size:1.05rem}.service-hero-icon{position:relative;font-size:7rem;color:#f5d79b;opacity:.9}.service-section-heading h2,.service-programs h2{margin:0 0 5px;font-size:1.3rem;font-weight:800;color:#274656}.service-section-heading p{margin:0;color:#718088;font-size:.9rem}.service-link-card{display:block;height:100%;padding:28px;border:1px solid #e5eceb;border-radius:18px;background:#fff;color:#294352;text-decoration:none;box-shadow:0 8px 22px #1d45500d;transition:.2s}.service-link-card:hover{transform:translateY(-5px);color:#1b736d;box-shadow:0 17px 32px #1d455024}.service-link-card>i{display:grid;place-items:center;width:52px;height:52px;margin-bottom:22px;border-radius:15px;background:#e4f3f0;color:#19736b;font-size:1.35rem}.service-link-card h2{font-size:1.12rem;font-weight:800}.service-link-card p{min-height:53px;color:#687883;font-size:.9rem}.service-link-card span{font-size:.85rem;font-weight:800;color:#b38b49}.service-empty{padding:45px 20px;border:1px dashed #bfd0d2;border-radius:16px;background:#fff;text-align:center;color:#728188}.service-empty>i{font-size:2rem;color:#b38b49}.service-empty h2{margin:13px 0 5px;color:#395362;font-size:1.1rem;font-weight:800}.service-empty p{margin:0;font-size:.88rem}.service-programs article{display:flex;align-items:center;gap:13px;padding:17px 20px;border-radius:14px;background:#fff;border:1px solid #e5eceb}.service-programs article>i{color:#b38b49}.service-programs strong,.service-programs small{display:block}.service-programs small{color:#74818a;font-size:.78rem}@media(max-width:576px){.service-hero{padding:30px 25px}.service-hero-icon{display:none}}</style>
@endsection
