@extends('frontend.layouts.public')

@section('content')
<style>
    .duty-page{padding:40px 0 72px;background:linear-gradient(180deg,#f2f9fb 0,#fff 62%)}
    .duty-heading{margin-bottom:23px}.duty-heading h1{margin:0;color:#193f54;font-size:2rem;font-weight:900}.duty-heading p{margin:8px 0 0;color:#71848d}.duty-heading:after{display:block;width:48px;height:3px;margin-top:12px;border-radius:5px;background:#b89a60;content:''}
    .duty-task{position:relative;overflow:hidden;padding:27px;border:1px solid #e1e9e9;border-left:4px solid #b89a60;border-radius:17px;background:linear-gradient(112deg,#edf3fc,#fff9ed);box-shadow:0 11px 27px #173f5010}.duty-task:after{position:absolute;width:150px;height:150px;top:-85px;right:-42px;border-radius:50%;background:#f0d7962a;content:''}.duty-task>*{position:relative;z-index:1}.duty-label{display:flex;align-items:center;gap:12px;margin-bottom:15px;color:#b29257;font-size:1.05rem;font-weight:900}.duty-label i{display:grid;width:43px;height:43px;place-items:center;border-radius:11px;background:#b89a60;color:#fff}.duty-summary{margin:0 0 17px;color:#536872;font-size:.87rem;line-height:1.7}.duty-accordion{overflow:hidden;border:1px solid #e1eaf0;border-radius:10px;background:#fff}.duty-accordion summary{display:flex;align-items:center;gap:8px;padding:12px 15px;background:#b89a60;color:#fff;cursor:pointer;font-size:.8rem;font-weight:900;list-style:none}.duty-accordion summary::-webkit-details-marker{display:none}.duty-accordion summary:after{margin-left:auto;font-family:'Font Awesome 6 Free';font-weight:900;content:'\f107';transition:.2s}.duty-accordion[open] summary:after{transform:rotate(180deg)}.duty-accordion p{margin:0;padding:16px;color:#536872;font-size:.82rem;line-height:1.65;white-space:pre-line}
    .duty-functions-title{margin:32px 0 17px;color:#24485a;font-size:1.35rem;font-weight:900}.duty-functions-title:after{display:block;width:38px;height:3px;margin-top:9px;background:#b89a60;content:''}.duty-function-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:18px}.duty-function{padding:23px;border:1px solid #ddebf0;border-radius:16px;background:#fff;box-shadow:0 8px 22px #173f5010;transition:.2s}.duty-function:hover{transform:translateY(-5px);box-shadow:0 16px 29px #173f501d}.duty-function-icon{display:grid;width:40px;height:40px;margin-bottom:13px;place-items:center;border-radius:11px;background:#b89a60;color:#fff}.duty-function h2{margin:0 0 11px;color:#b29257;font-size:.88rem;font-weight:900}.duty-function ul{padding:0;margin:0;list-style:none}.duty-function li{position:relative;padding:5px 0 5px 18px;color:#647982;font-size:.76rem;line-height:1.55}.duty-function li:before{position:absolute;top:6px;left:0;color:#b89a60;font-family:'Font Awesome 6 Free';font-weight:900;content:'\f00c'}
    @media(max-width:991px){.duty-function-grid{grid-template-columns:1fr}}@media(max-width:576px){.duty-page{padding:25px 0 52px}.duty-heading h1{font-size:1.55rem}.duty-task{padding:21px}.duty-function-grid{gap:13px}}
</style>
@php
    $defaultFunctions = [
        ['icon' => 'fa-clipboard-list', 'title' => 'Perumusan Kebijakan', 'items' => ['Perumusan kebijakan di bidang perumahan dan kawasan permukiman.']],
        ['icon' => 'fa-calendar-check', 'title' => 'Pembinaan', 'items' => ['Pembinaan teknis di bidang perumahan dan kawasan permukiman.', 'Pembinaan unit pelaksana teknis dinas.', 'Pembinaan kelompok jabatan fungsional.']],
        ['icon' => 'fa-list-check', 'title' => 'Pelaksanaan Program', 'items' => ['Pelaksanaan kebijakan di bidang perumahan dan kawasan permukiman.', 'Pelaksanaan administrasi dinas perumahan dan kawasan permukiman sesuai lingkup tugasnya.', 'Pelaksanaan evaluasi dan pelaporan di bidang perumahan dan kawasan permukiman.', 'Pelaksanaan fungsi lain yang diberikan oleh Gubernur terkait tugas dan fungsinya.']],
    ];
    $functions = $setting?->duty_functions ?: $defaultFunctions;
@endphp
<main class="duty-page"><div class="container"><header class="duty-heading"><h1>TUGAS POKOK DAN FUNGSI</h1><p>Dinas Perumahan dan Kawasan Pemukiman Provinsi Maluku</p></header><section class="duty-task"><div class="duty-label"><i class="fas fa-briefcase"></i><span>Tugas Pokok Dinas</span></div><p class="duty-summary">Dinas Perumahan dan Kawasan Pemukiman Provinsi Maluku mempunyai tugas melaksanakan urusan pemerintahan daerah di bidang perumahan dan kawasan permukiman.</p><details class="duty-accordion" open><summary><i class="fas fa-list-check"></i>Tugas Pokok</summary><p>{{ $setting?->duties ?: 'Membantu Gubernur dalam melaksanakan urusan pemerintahan bidang perumahan dan kawasan permukiman serta tugas pembantuan yang ditugaskan kepada daerah Provinsi.' }}</p></details></section><section><h2 class="duty-functions-title">Fungsi</h2><div class="duty-function-grid">@foreach($functions as $function)<article class="duty-function"><div class="duty-function-icon"><i class="fas {{ $function['icon'] ?? 'fa-list-check' }}"></i></div><h2>{{ $function['title'] }}</h2><ul>@foreach($function['items'] as $item)<li>{{ $item }}</li>@endforeach</ul></article>@endforeach</div></section></div></main>
@endsection
