@include('console.nav', ['title' => 'Pimpinan Maluku'])

@php($positionLabels = ['gubernur' => 'Gubernur', 'wakil_gubernur' => 'Wakil Gubernur', 'sekda' => 'Sekretaris Daerah'])
<div class="d-flex flex-wrap justify-content-between align-items-center gap-3 mb-4"><div><p class="text-secondary mb-0">Kelola data Gubernur, Wakil Gubernur, dan Sekretaris Daerah Provinsi Maluku.</p></div><button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#leaderCreate"><i class="fa fa-plus me-1"></i>Tambah Pimpinan</button></div>

<div class="card overflow-hidden"><div class="p-3 border-bottom d-flex justify-content-between align-items-center"><h2 class="h5 mb-0"><i class="fa fa-user-tie text-primary me-2"></i>Daftar Pimpinan</h2><span class="badge text-bg-primary">{{ $leaders->count() }} data</span></div><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Pimpinan</th><th>Jabatan</th><th>Periode</th><th>Urutan</th><th>Status</th><th class="text-end">Aksi</th></tr></thead><tbody>@forelse($leaders as $leader)<tr><td><div class="d-flex align-items-center gap-2"><img src="{{ $leader->photo_path ? $leader->photo_url : asset('assets/img/user.png') }}" alt="{{ $leader->name }}" class="rounded-circle" style="width:38px;height:38px;object-fit:cover"><strong>{{ $leader->name }}</strong></div></td><td><span class="badge text-bg-light text-primary">{{ $positionLabels[$leader->position] ?? $leader->position }}</span></td><td>{{ $leader->period ?: '-' }}</td><td>{{ $leader->sort_order }}</td><td><span class="badge text-bg-{{ $leader->is_active ? 'success' : 'secondary' }}">{{ $leader->is_active ? 'Aktif' : 'Nonaktif' }}</span></td><td class="text-end"><button class="btn btn-sm btn-outline-primary" data-bs-toggle="modal" data-bs-target="#leaderEdit{{ $leader->id }}" title="Edit"><i class="fa fa-pen"></i></button><form method="post" action="/console/pimpinan/{{ $leader->id }}" class="d-inline">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger js-swal-delete" data-message="Hapus data {{ $leader->name }}?" title="Hapus"><i class="fa fa-trash"></i></button></form></td></tr>@empty<tr><td colspan="6" class="text-center text-secondary py-5">Belum ada data pimpinan.</td></tr>@endforelse</tbody></table></div></div>

@include('console.leader-form', ['id' => 'leaderCreate', 'action' => '/console/pimpinan', 'leader' => null, 'positionLabels' => $positionLabels])
@foreach($leaders as $leader) @include('console.leader-form', ['id' => 'leaderEdit'.$leader->id, 'action' => '/console/pimpinan/'.$leader->id, 'leader' => $leader, 'positionLabels' => $positionLabels]) @endforeach
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script><script>document.querySelectorAll('.js-leader-photo').forEach(input=>input.addEventListener('change',function(){const file=this.files?.[0],preview=document.getElementById(this.dataset.preview);if(file&&preview)preview.src=URL.createObjectURL(file)}));</script>
@include('console.end')
