@include('console.nav',['title'=>'Berita'])

<div class="d-flex flex-wrap justify-content-between align-items-center gap-3 mb-4"><p class="text-secondary mb-0">Kelola berita yang ditampilkan pada website publik.</p><button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#newsCreate"><i class="fa fa-plus me-1"></i>Tambah Berita</button></div>
<form method="get" class="card card-body mb-4"><div class="row g-3 align-items-end"><div class="col-lg-5"><label class="form-label">Cari berita</label><input type="search" name="cari" value="{{ request('cari') }}" class="form-control" placeholder="Judul atau ringkasan berita"></div><div class="col-md-3"><label class="form-label">Kategori</label><select name="kategori" class="form-select"><option value="">Semua kategori</option>@foreach($categories as $category)<option value="{{ $category }}" @selected(request('kategori')===$category)>{{ $category }}</option>@endforeach</select></div><div class="col-md-2"><label class="form-label">Status</label><select name="status" class="form-select"><option value="">Semua status</option><option value="published" @selected(request('status')==='published')>Publikasi</option><option value="draft" @selected(request('status')==='draft')>Draft</option></select></div><div class="col-md-2 d-flex gap-2"><button class="btn btn-primary"><i class="fa fa-filter me-1"></i>Filter</button><a href="/console/berita" class="btn btn-light border">Reset</a></div></div></form>
<div class="card overflow-hidden"><div class="p-3 border-bottom d-flex justify-content-between align-items-center"><h2 class="h5 mb-0"><i class="fa fa-newspaper text-primary me-2"></i>Daftar Berita</h2><span class="badge text-bg-secondary">{{ $posts->total() }} data</span></div><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Berita</th><th>Kategori</th><th>Status</th><th>Tanggal</th><th class="text-end">Aksi</th></tr></thead><tbody>@forelse($posts as $post)<tr><td><strong>{{ $post->title }}</strong><br><small class="text-secondary">{{ Str::limit($post->excerpt,80) }}</small></td><td>{{ $post->category ?: '-' }}</td><td><span class="badge text-bg-{{ $post->status==='published'?'success':'secondary' }}">{{ $post->status==='published'?'Publikasi':'Draft' }}</span></td><td>{{ optional($post->published_at)->format('d M Y') ?: '-' }}</td><td class="text-end"><button class="btn btn-sm btn-outline-primary" title="Edit" data-bs-toggle="modal" data-bs-target="#news{{ $post->id }}"><i class="fa fa-pen"></i></button><form method="post" action="/console/berita/{{ $post->id }}" class="d-inline">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger js-swal-delete" data-message="Hapus berita {{ $post->title }}?" title="Hapus"><i class="fa fa-trash"></i></button></form></td></tr>@empty<tr><td colspan="5" class="text-center text-secondary py-5">Berita tidak ditemukan.</td></tr>@endforelse</tbody></table></div></div>
<div class="mt-3">{{ $posts->links() }}</div>
@include('console.news-form',['id'=>'newsCreate','action'=>'/console/berita','post'=>null])
@foreach($posts as $post)
    @include('console.news-form',['id'=>'news'.$post->id,'action'=>'/console/berita/'.$post->id,'post'=>$post])
@endforeach
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
@include('console.end')
