@include('console.nav',['title'=>'Pejabat Struktural'])

<div class="d-flex flex-wrap justify-content-between align-items-center gap-3 mb-4"><div><p class="text-secondary mb-0">Kelola profil pejabat untuk kartu, filter, dan detail profil frontend.</p></div><button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#officialCreate"><i class="fa fa-user-plus me-1"></i>Tambah Pejabat</button></div>
<div class="card overflow-hidden"><div class="p-3 border-bottom d-flex justify-content-between align-items-center"><h2 class="h5 mb-0"><i class="fa fa-user-tie text-primary me-2"></i>Daftar Pejabat</h2><span class="badge text-bg-secondary">{{ $officials->total() }} data</span></div><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Pejabat</th><th>Jabatan / Unit</th><th>NIP</th><th>Status</th><th class="text-end">Aksi</th></tr></thead><tbody>@forelse($officials as $official)<tr><td><strong>{{ $official->name }}</strong><br><small class="text-secondary">{{ $official->echelon ?: '-' }}</small></td><td>{{ $official->position }}<br><small class="text-secondary">{{ $official->unit ?: '-' }}</small></td><td>{{ $official->nip ?: '-' }}</td><td><span class="badge text-bg-{{ $official->is_active ? 'success' : 'secondary' }}">{{ $official->is_active ? 'Aktif' : 'Nonaktif' }}</span></td><td class="text-end"><button class="btn btn-sm btn-outline-primary" data-bs-toggle="modal" data-bs-target="#official{{ $official->id }}" title="Edit"><i class="fa fa-pen"></i></button><form method="post" action="/console/pejabat/{{ $official->id }}" class="d-inline">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger js-swal-delete" data-message="Hapus data pejabat {{ $official->name }}?" title="Hapus"><i class="fa fa-trash"></i></button></form></td></tr>@empty<tr><td colspan="5" class="text-center text-secondary py-5">Belum ada data pejabat.</td></tr>@endforelse</tbody></table></div></div>
<div class="mt-3">{{ $officials->links() }}</div>
@include('console.official-form',['id'=>'officialCreate','action'=>'/console/pejabat','official'=>null])
@foreach($officials as $official)
    @include('console.official-form',['id'=>'official'.$official->id,'action'=>'/console/pejabat/'.$official->id,'official'=>$official])
@endforeach
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
@include('console.end')
