@include('console.nav',['title'=>'Data Penerima Bantuan MBBR'])
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
@if($errors->any())<div class="alert alert-danger"><strong>Data belum dapat disimpan.</strong><ul class="mb-0 mt-1">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<div class="d-flex justify-content-between align-items-center mb-4"><div><p class="text-secondary mb-0">Kelola data penerima pembangunan perumahan, kawasan permukiman, dan PSU.</p></div><div class="d-flex gap-2"><a class="btn btn-success" href="/console/program-mbbr/import-penerima"><i class="fa fa-file-import me-1"></i>Import</a><a class="btn btn-info text-white" href="/console/penerima/export"><i class="fa fa-file-export me-1"></i>Export</a><button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#recipientCreate"><i class="fa fa-plus me-1"></i>Tambah</button></div></div>
<div class="row g-3 mb-4">@foreach([['Total Data',$total,'primary','fa-users'],['Swakelola',$swakelola,'success','fa-house'],['Kontraktual KP/PSU',$contractual,'warning','fa-file-signature'],['Kawasan Kumuh',$slumArea,'danger','fa-city']] as [$label,$number,$color,$icon])<div class="col-md-6 col-xl-3"><div class="card p-3 border-start border-4 border-{{ $color }}"><small class="text-secondary text-uppercase">{{ $label }}</small><strong class="display-6">{{ $number }}</strong><i class="fa {{ $icon }} text-{{ $color }} opacity-50 position-absolute end-0 me-4 mt-4 fs-3"></i></div></div>@endforeach</div>
<div class="card p-3 mb-4"><form class="row g-3 align-items-end" method="get">
<div class="col-md-2"><label class="form-label">Tahun Anggaran</label><select id="recipientYear" name="fiscal_year" class="form-select"><option value="">Pilih Tahun</option>@foreach($years as $year)<option value="{{ $year }}" @selected(request('fiscal_year')==$year)>{{ $year }}</option>@endforeach</select></div>
<div class="col-md-2"><label class="form-label">Jenis Program</label><select id="recipientProgramType" name="program_type_id" class="form-select"><option value="">Pilih Tahun dahulu</option>@foreach($types as $type)<option value="{{ $type->id }}" @selected(request('program_type_id')==$type->id)>{{ $type->name }}</option>@endforeach</select></div>
<div class="col-md-2"><label class="form-label">Kategori</label><select name="work_category" class="form-select"><option value="">Semua</option><option value="swakelola" @selected(request('work_category')==='swakelola')>Swakelola</option><option value="kontraktual" @selected(request('work_category')==='kontraktual')>Kontraktual</option></select></div>
<div class="col-md-2"><label class="form-label">Status Kawasan</label><select name="area_status" class="form-select"><option value="">Semua</option><option value="kawasan_kumuh" @selected(request('area_status')==='kawasan_kumuh')>Kawasan Kumuh</option><option value="bukan_kawasan_kumuh" @selected(request('area_status')==='bukan_kawasan_kumuh')>Bukan Kumuh</option></select></div>
<div class="col-md-2"><label class="form-label">Status Pelaksanaan</label><select name="status" class="form-select"><option value="">Semua</option><option value="waiting" @selected(request('status')==='waiting')>Menunggu</option><option value="process" @selected(request('status')==='process')>Dalam Proses</option><option value="completed" @selected(request('status')==='completed')>Selesai</option></select></div>
<div class="col-md-2"><label class="form-label">Desa</label><select name="village_id" class="form-select"><option value="">Semua Desa</option>@foreach($villages as $village)<option value="{{ $village->id }}" @selected(request('village_id')==$village->id)>{{ $village->name }}</option>@endforeach</select></div>
<div class="col-md-3"><label class="form-label">Sub Program</label><select id="recipientSubProgram" name="mbbr_program_id" class="form-select"><option value="">Pilih jenis program</option>@foreach($programs as $program)<option value="{{ $program->id }}" data-type="{{ $program->mbbr_program_type_id }}" data-year="{{ $program->fiscal_year }}" @selected(request('mbbr_program_id')==$program->id)>{{ $program->name }}</option>@endforeach</select></div>
<div class="col-md-3"><label class="form-label">Cari</label><div class="input-group"><input name="cari" class="form-control" value="{{ request('cari') }}" placeholder="Nama/paket/kontraktor"><button class="btn btn-secondary"><i class="fa fa-filter"></i></button><a href="/console/penerima" class="btn btn-outline-primary"><i class="fa fa-rotate-left"></i></a></div></div>
</form></div>
<div class="card overflow-hidden"><div class="p-3 border-bottom"><h2 class="h5 mb-0"><i class="fa fa-table-list text-primary me-2"></i>Daftar Data Penerima <span class="badge text-bg-secondary">{{ $recipients->total() }}</span></h2></div><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>No</th><th>Penerima / Paket</th><th>Kategori</th><th>Status Kawasan</th><th>Program</th><th>Progress</th><th>Aksi</th></tr></thead><tbody>@forelse($recipients as $recipient)<tr><td>{{ $recipients->firstItem()+$loop->index }}</td><td><strong>{{ $recipient->name }}</strong><br><small>{{ $recipient->village?->name ?: '-' }}</small></td><td><span class="badge text-bg-{{ $recipient->work_category==='kontraktual'?'primary':'success' }}">{{ $recipient->work_category==='kontraktual'?'Kontraktual':'Swakelola' }}</span></td><td><span class="badge text-bg-{{ $recipient->area_status==='kawasan_kumuh'?'danger':($recipient->area_status==='bukan_kawasan_kumuh'?'secondary':'light') }}">{{ ['kawasan_kumuh'=>'Kawasan Kumuh','bukan_kawasan_kumuh'=>'Bukan Kumuh'][$recipient->area_status] ?? 'Belum diisi' }}</span></td><td>{{ $recipient->program?->type?->name ?: '-' }}<br><small>{{ $recipient->program?->name ?: '-' }}</small></td><td>{{ number_format($recipient->progress,2) }}%<br><small>{{ ['completed'=>'Selesai','process'=>'Proses','waiting'=>'Menunggu'][$recipient->status] }}</small></td><td class="text-nowrap"><button class="btn btn-sm btn-info text-white" data-bs-toggle="modal" data-bs-target="#detailRecipient{{ $recipient->id }}"><i class="fa fa-eye"></i></button><button class="btn btn-sm btn-outline-primary" data-bs-toggle="modal" data-bs-target="#recipient{{ $recipient->id }}"><i class="fa fa-pen"></i></button><form method="post" action="/console/penerima/{{ $recipient->id }}" class="d-inline">@csrf @method('DELETE')<button class="btn btn-sm btn-danger" onclick="return confirm('Hapus data penerima?')"><i class="fa fa-trash"></i></button></form></td></tr>@empty<tr><td colspan="7" class="text-center text-secondary py-4">Data penerima belum tersedia.</td></tr>@endforelse</tbody></table></div></div><div class="mt-3">{{ $recipients->links() }}</div>
@include('console.recipient-form',['id'=>'recipientCreate','action'=>'/console/penerima','recipient'=>null])
@foreach($recipients as $recipient)@include('console.recipient-detail',['recipient'=>$recipient])@include('console.recipient-form',['id'=>'recipient'.$recipient->id,'action'=>'/console/penerima/'.$recipient->id,'recipient'=>$recipient])@endforeach
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script><script>function cascade(year,type,program){const apply=()=>{const y=year.value,t=type.value;type.disabled=!y;[...type.options].slice(1).forEach(option=>{const has=[...program.options].slice(1).some(item=>item.dataset.year===y&&item.dataset.type===option.value);option.hidden=!has;option.disabled=!has});if(!y||type.selectedOptions[0]?.disabled)type.value='';const currentType=type.value;program.disabled=!currentType;program.options[0].text=currentType?'Pilih sub program':'Pilih jenis program dahulu';[...program.options].slice(1).forEach(option=>{const allowed=option.dataset.year===y&&option.dataset.type===currentType;option.hidden=!allowed;option.disabled=!allowed});if(!currentType||program.selectedOptions[0]?.disabled)program.value=''};year.addEventListener('change',apply);type.addEventListener('change',apply);apply()}cascade(document.getElementById('recipientYear'),document.getElementById('recipientProgramType'),document.getElementById('recipientSubProgram'));document.querySelectorAll('.recipient-form-year').forEach(year=>cascade(year,year.closest('form').querySelector('.recipient-form-type'),year.closest('form').querySelector('.recipient-form-program')));@if($errors->any())new bootstrap.Modal(document.getElementById('recipientCreate')).show();@endif</script>@include('console.end')
