@include('console.nav', ['title' => 'Pendataan RLTH'])
<div class="d-flex flex-wrap justify-content-between align-items-center gap-3 mb-4"><p class="text-secondary mb-0">Kelola data Rumah Tidak Layak Huni, kondisi bangunan, koordinat, dan dokumentasi rumah.</p><div class="d-flex gap-2"><a class="btn btn-outline-primary" href="/console/pendataan-rlth/template"><i class="fa fa-download me-1"></i>Template</a><button class="btn btn-success" data-bs-toggle="modal" data-bs-target="#rlthImport"><i class="fa fa-file-import me-1"></i>Import</button><button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#rlthCreate"><i class="fa fa-plus me-1"></i>Tambah Data</button></div></div>
<div class="row g-3 mb-4"><div class="col-md-6"><div class="card p-3"><small class="text-secondary">Total Data RTLH</small><strong class="fs-3">{{ number_format($total) }}</strong></div></div><div class="col-md-6"><div class="card p-3"><small class="text-secondary">Memiliki Koordinat Peta</small><strong class="fs-3">{{ number_format($mapped) }}</strong></div></div></div>
<form class="card p-3 mb-4"><div class="row g-3 align-items-end"><div class="col-md-4"><label class="form-label">Cari</label><input name="cari" value="{{ request('cari') }}" class="form-control" placeholder="Nama, NIK, atau desa"></div><div class="col-md-2"><label class="form-label">Tahun</label><select name="tahun" class="form-select"><option value="">Semua</option>@foreach($years as $year)<option @selected(request('tahun')==$year)>{{ $year }}</option>@endforeach</select></div><div class="col-md-3"><label class="form-label">Kabupaten/Kota</label><select name="kabupaten" class="form-select"><option value="">Semua</option>@foreach($regencies as $regency)<option @selected(request('kabupaten')===$regency)>{{ $regency }}</option>@endforeach</select></div><div class="col-md-3"><label class="form-label">Kerusakan Atap</label><select name="kerusakan" class="form-select"><option value="">Semua</option>@foreach($damages as $damage)<option @selected(request('kerusakan')===$damage)>{{ $damage }}</option>@endforeach</select></div><div class="col-12"><button class="btn btn-primary"><i class="fa fa-filter me-1"></i>Filter</button><a href="/console/pendataan-rlth" class="btn btn-light">Reset</a></div></div></form>
<div class="card overflow-hidden"><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Nama</th><th>Wilayah</th><th>Kondisi Atap</th><th>Koordinat</th><th>Dokumentasi</th><th class="text-end">Aksi</th></tr></thead><tbody>@forelse($records as $record)<tr><td><strong>{{ $record->name }}</strong><br><small class="text-secondary">{{ $record->survey_year ?: '-' }}</small></td><td>{{ $record->regency_name ?: '-' }}<br><small>{{ $record->village_name ?: '-' }}</small></td><td>{{ $record->roof_damage_level ?: '-' }}</td><td><small>{{ $record->latitude && $record->longitude ? $record->latitude.', '.$record->longitude : 'Belum diisi' }}</small></td><td><span class="badge text-bg-{{ $record->photo_front_path ? 'success':'secondary' }}">{{ $record->photo_front_path ? 'Ada foto':'Belum ada' }}</span></td><td class="text-end"><button class="btn btn-sm btn-outline-primary" data-bs-toggle="modal" data-bs-target="#rlth{{ $record->id }}"><i class="fa fa-pen"></i></button><form method="post" action="/console/pendataan-rlth/{{ $record->id }}" class="d-inline">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger js-swal-delete" data-message="Hapus data {{ $record->name }}?"><i class="fa fa-trash"></i></button></form></td></tr>@empty<tr><td colspan="6" class="text-center text-secondary py-5">Belum ada data RLTH.</td></tr>@endforelse</tbody></table></div>@if($records->hasPages())<div class="p-3 border-top">{{ $records->links() }}</div>@endif</div>
@include('console.rlth-record-form', ['id'=>'rlthCreate','action'=>'/console/pendataan-rlth','record'=>null])
@foreach($records as $record)@include('console.rlth-record-form', ['id'=>'rlth'.$record->id,'action'=>'/console/pendataan-rlth/'.$record->id,'record'=>$record])@endforeach
<div class="modal fade" id="rlthImport" tabindex="-1"><div class="modal-dialog"><form method="post" action="/console/pendataan-rlth/import" enctype="multipart/form-data" class="modal-content">@csrf<div class="modal-header"><h2 class="fs-5"><i class="fa fa-file-import me-2"></i>Import Pendataan RTLH</h2><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="alert alert-light border small"><strong>Gunakan template RTLH.</strong><br>File Excel <code>.xlsx</code> atau CSV <code>.csv</code> dapat diunggah. Baris dengan NIK yang sama akan diperbarui; tanpa NIK, data diperiksa berdasarkan nama, desa, dan tahun.</div><label class="form-label">File Template RTLH</label><input type="file" name="file" accept=".xlsx,.csv,.txt" class="form-control" required><a href="/console/pendataan-rlth/template" class="small d-inline-block mt-3"><i class="fa fa-download me-1"></i>Unduh template CSV</a></div><div class="modal-footer"><button type="button" class="btn btn-light" data-bs-dismiss="modal">Batal</button><button class="btn btn-success" type="submit"><i class="fa fa-file-import me-1"></i>Import Data</button></div></form></div></div>
<script>document.addEventListener('DOMContentLoaded',()=>{const form=document.querySelector('form[action="/console/pendataan-rlth/import"]');if(!form)return;form.addEventListener('submit',event=>{event.preventDefault();const button=form.querySelector('button[type="submit"]');button.disabled=true;button.innerHTML='<span class="spinner-border spinner-border-sm me-2"></span>Mengimpor...';Swal.fire({title:'Mengimpor data RTLH',text:'Mohon tunggu, file sedang diproses.',allowOutsideClick:false,allowEscapeKey:false,didOpen:()=>Swal.showLoading()});setTimeout(()=>form.submit(),120)})})</script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
@include('console.end')
