@include('console.nav',['title'=>'Manajemen User'])

<div class="d-flex flex-wrap justify-content-between align-items-center gap-3 mb-4"><p class="text-secondary mb-0">Kelola akun administrator dan editor website.</p><button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#userCreate"><i class="fa fa-user-plus me-1"></i>Tambah User</button></div>
<form method="get" class="card card-body mb-4"><div class="row g-3 align-items-end"><div class="col-lg-5"><label class="form-label">Cari pengguna</label><input type="search" name="cari" value="{{ request('cari') }}" class="form-control" placeholder="Nama, username, atau email"></div><div class="col-md-3"><label class="form-label">Peran</label><select name="role" class="form-select"><option value="">Semua peran</option><option value="admin" @selected(request('role')==='admin')>Admin</option><option value="editor" @selected(request('role')==='editor')>Editor</option></select></div><div class="col-md-2"><label class="form-label">Status</label><select name="status" class="form-select"><option value="">Semua status</option><option value="active" @selected(request('status')==='active')>Aktif</option><option value="inactive" @selected(request('status')==='inactive')>Nonaktif</option></select></div><div class="col-md-2 d-flex gap-2"><button class="btn btn-primary"><i class="fa fa-filter me-1"></i>Filter</button><a href="/console/users" class="btn btn-light border">Reset</a></div></div></form>
<div class="card overflow-hidden"><div class="p-3 border-bottom d-flex justify-content-between align-items-center"><h2 class="h5 mb-0"><i class="fa fa-users text-primary me-2"></i>Daftar Pengguna</h2><span class="badge text-bg-secondary">{{ $users->total() }} akun</span></div><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Pengguna</th><th>Email</th><th>Peran</th><th>Status</th><th class="text-end">Aksi</th></tr></thead><tbody>@forelse($users as $user)<tr><td><strong>{{ $user->name }}</strong><br><small class="text-secondary">@{{ $user->username }}</small></td><td>{{ $user->email ?: '-' }}</td><td><span class="badge text-bg-{{ $user->role==='admin'?'primary':'info' }}">{{ ucfirst($user->role) }}</span></td><td><span class="badge text-bg-{{ $user->is_active?'success':'secondary' }}">{{ $user->is_active?'Aktif':'Nonaktif' }}</span></td><td class="text-end"><button class="btn btn-sm btn-outline-primary" data-bs-toggle="modal" data-bs-target="#user{{ $user->id }}" title="Edit"><i class="fa fa-pen"></i></button><form class="d-inline" method="post" action="/console/users/{{ $user->id }}">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger js-swal-delete" data-message="Hapus akun {{ $user->username }}?" title="Hapus"><i class="fa fa-trash"></i></button></form></td></tr>@empty<tr><td colspan="5" class="text-center text-secondary py-5">Pengguna tidak ditemukan.</td></tr>@endforelse</tbody></table></div></div>
<div class="mt-3">{{ $users->links() }}</div>
@include('console.user-form',['id'=>'userCreate','action'=>'/console/users','user'=>null])
@foreach($users as $user)
    @include('console.user-form',['id'=>'user'.$user->id,'action'=>'/console/users/'.$user->id,'user'=>$user])
@endforeach
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
@include('console.end')
