@php($profileActive = request()->is('profil-dinas','visi-misi','tugas-pokok-fungsi','struktur-organisasi','profil-pejabat'))
@php($activityActive = request()->is('agenda-kegiatan','program-kegiatan'))
@php($sigaprumabetaActive = request()->is('pendataan-rlth','geomap','data-usulan','sadata-kp','sadata-psu','kawasan-kumuh'))
<div class="top-header"><div class="container d-flex justify-content-between"><span>{{ $setting?->phone }}</span><span>{{ $setting?->email }}</span></div></div>
<header class="main-header"><div class="container"><div class="logo-section"><img src="{{ $setting?->logo_path ? asset('storage/'.$setting->logo_path) : asset('assets/img/logo.png') }}" class="logo-img" alt="Logo"><div class="logo-text"><h1>{{ strtoupper($setting?->agency_name ?? 'DINAS PERUMAHAN DAN KAWASAN PEMUKIMAN') }}</h1><p>PROVINSI MALUKU</p></div></div></div></header>
<nav class="navbar navbar-expand-lg navbar-light main-nav sticky-top"><div class="container"><button class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#publicNav"><span class="navbar-toggler-icon"></span></button><div class="collapse navbar-collapse" id="publicNav"><ul class="navbar-nav me-auto">
    <li class="nav-item"><a class="nav-link {{ request()->path()==='/' ? 'menu-active' : '' }}" href="/"><i class="fas fa-home me-1"></i> BERANDA</a></li>
    <li class="nav-item dropdown mega-dropdown"><a class="nav-link dropdown-toggle {{ $profileActive ? 'menu-active' : '' }}" href="#" data-bs-toggle="dropdown"><i class="fas fa-building me-1"></i> PROFIL</a><div class="dropdown-menu mega-menu"><div class="row g-0"><div class="col-md-6"><section class="mega-menu-section"><h6>Profil Dinas</h6><a class="{{ request()->is('profil-dinas')?'menu-active':'' }}" href="/profil-dinas"><i class="fas fa-landmark"></i> Profil Dinas</a><a class="{{ request()->is('visi-misi')?'menu-active':'' }}" href="/visi-misi"><i class="fas fa-eye"></i> Visi Misi</a><a class="{{ request()->is('tugas-pokok-fungsi')?'menu-active':'' }}" href="/tugas-pokok-fungsi"><i class="fas fa-list-check"></i> Tugas Pokok & Fungsi</a></section></div><div class="col-md-6"><section class="mega-menu-section border-start"><h6>Organisasi & Pimpinan</h6><a class="{{ request()->is('struktur-organisasi')?'menu-active':'' }}" href="/struktur-organisasi"><i class="fas fa-sitemap"></i> Struktur Organisasi</a><a class="{{ request()->is('profil-pejabat')?'menu-active':'' }}" href="/profil-pejabat"><i class="fas fa-user-tie"></i> Profil Pejabat Struktural</a></section></div></div></div></li>
    <li class="nav-item dropdown mega-dropdown"><a class="nav-link dropdown-toggle {{ $activityActive ? 'menu-active' : '' }}" href="#" data-bs-toggle="dropdown"><i class="fas fa-calendar-alt me-1"></i> KEGIATAN</a><div class="dropdown-menu mega-menu activity-mega"><section class="mega-menu-section"><h6>Kegiatan Dinas</h6><a class="{{ request()->is('agenda-kegiatan')?'menu-active':'' }}" href="/agenda-kegiatan"><i class="fas fa-calendar-days"></i> Agenda Kegiatan</a><a class="{{ request()->is('program-kegiatan')?'menu-active':'' }}" href="/program-kegiatan"><i class="fas fa-diagram-project"></i> Program Kegiatan</a></section></div></li>
    <li class="nav-item"><a class="nav-link {{ request()->is('layanan-pkp') ? 'menu-active' : '' }}" href="/layanan-pkp"><i class="fas fa-handshake-angle me-1"></i> LAYANAN PKP</a></li>
    <li class="nav-item dropdown mega-dropdown"><a class="nav-link dropdown-toggle {{ $sigaprumabetaActive ? 'menu-active' : '' }}" href="#" data-bs-toggle="dropdown"><i class="fas fa-map-location-dot me-1"></i> SIGAPRUMABETA</a><div class="dropdown-menu mega-menu sigaprumabeta-mega"><div class="row g-0"><div class="col-md-6"><section class="mega-menu-section"><h6>Sadata Perumahan</h6><a class="{{ request()->is('pendataan-rlth')?'menu-active':'' }}" href="/pendataan-rlth"><i class="fas fa-house-crack"></i> Sadata RTLH</a><a class="{{ request()->is('geomap')?'menu-active':'' }}" href="/geomap"><i class="fas fa-map"></i> Sadata Sebaran Kegiatan</a><a class="{{ request()->is('data-usulan')?'menu-active':'' }}" href="/data-usulan"><i class="fas fa-file-circle-plus"></i> Data Usulan</a></section></div><div class="col-md-6"><section class="mega-menu-section border-start"><h6>Sadata KP dan PSU</h6><a class="{{ request()->is('sadata-kp')?'menu-active':'' }}" href="/sadata-kp"><i class="fas fa-city"></i> Sadata KP</a><a class="{{ request()->is('sadata-psu')?'menu-active':'' }}" href="/sadata-psu"><i class="fas fa-road"></i> Sadata PSU</a><a class="{{ request()->is('kawasan-kumuh')?'menu-active':'' }}" href="/kawasan-kumuh"><i class="fas fa-layer-group"></i> Kawasan Kumuh</a></section></div></div></div></li>
    @foreach(['berita'=>'BERITA','galeri'=>'GALERI','peraturan'=>'PERATURAN','informasi'=>'INFORMASI','unduhan'=>'UNDUHAN','kontak'=>'KONTAK'] as $url=>$label)<li class="nav-item"><a class="nav-link {{ request()->is($url) ? 'menu-active' : '' }}" href="/{{ $url }}">{{ $label }}</a></li>@endforeach
</ul></div></div></nav>
<style>.main-nav .nav-link.menu-active{position:relative;color:#a27a3b!important;font-weight:900!important}.main-nav .nav-link.menu-active:after{position:absolute;right:10px;bottom:3px;left:10px;height:3px;border-radius:6px;background:#c4a465;content:''}.main-nav .mega-menu a.menu-active{background:#f7ecd5!important;color:#8d682d!important;font-weight:800!important}.activity-mega{width:330px!important}@media(max-width:991px){.main-nav .nav-link.menu-active:after{right:auto;bottom:0;left:0;width:38px}.activity-mega{width:100%!important}}</style>
<style>@media(min-width:992px){.main-nav .mega-dropdown{position:relative!important}.main-nav .mega-menu{width:560px!important;right:auto!important;left:0!important;padding:16px!important}.main-nav .activity-mega{width:330px!important}.main-nav .sigaprumabeta-mega{width:620px!important}.main-nav .mega-menu .mega-menu-section{margin-bottom:0!important}}</style>
