@extends('frontend.layouts.public')

@section('content')
<style>
    .gallery-page{padding:38px 0 72px;background:linear-gradient(180deg,#f4fafb 0,#fff 68%)}
    .gallery-hero{max-width:750px;margin:0 auto 28px;text-align:center}.gallery-hero h1{margin:0;color:#183c51;font-size:2rem;font-weight:900}.gallery-hero p{margin:9px 0 0;color:#71828b}
    .gallery-tabs{display:flex;justify-content:center;flex-wrap:wrap;gap:10px;margin-bottom:28px}.gallery-tab{border:1px solid #d3e4e8;border-radius:999px;background:#fff;color:#507180;padding:10px 17px;font-size:.83rem;font-weight:800;transition:.2s}.gallery-tab.active,.gallery-tab:hover{border-color:#176eb1;background:#176eb1;color:#fff}.gallery-tab i{margin-right:5px}
    .gallery-section{margin-bottom:45px}.gallery-section-title{display:flex;align-items:center;gap:12px;margin:0 0 17px;color:#244b60;font-size:1.16rem;font-weight:900}.gallery-section-title i{display:grid;width:37px;height:37px;place-items:center;border-radius:10px;background:#e5f3fa;color:#1b77ba}.gallery-section-title span{color:#78929d;font-size:.75rem;font-weight:700}
    .gallery-card{height:100%;overflow:hidden;border:1px solid #dcebed;border-radius:16px;background:#fff;box-shadow:0 10px 24px #173e5410;transition:transform .2s,box-shadow .2s}.gallery-card:hover{transform:translateY(-5px);box-shadow:0 18px 30px #173e5422}.gallery-image,.gallery-video{position:relative;display:block;width:100%;height:205px;overflow:hidden;background:#e6f0f2}.gallery-image img{width:100%;height:100%;object-fit:cover;transition:transform .35s}.gallery-card:hover .gallery-image img{transform:scale(1.06)}.gallery-video iframe{width:100%;height:100%;border:0}.gallery-video .video-fallback{display:grid;width:100%;height:100%;place-items:center;background:linear-gradient(135deg,#1a4b65,#3687b6);color:#fff;text-decoration:none}.gallery-video .video-fallback i{font-size:2.4rem}.gallery-kind{position:absolute;top:11px;left:11px;padding:5px 9px;border-radius:999px;background:#173f57d9;color:#fff;font-size:.66rem;font-weight:900}.gallery-body{padding:16px}.gallery-body h2{margin:0 0 7px;color:#294c5f;font-size:1rem;font-weight:900;line-height:1.35}.gallery-body p{margin:0;color:#718892;font-size:.8rem;line-height:1.6}.gallery-empty{padding:32px;border:1px dashed #cadde2;border-radius:14px;color:#8197a1;text-align:center}.gallery-lightbox{position:fixed;inset:0;z-index:2000;display:none;align-items:center;justify-content:center;padding:22px;background:#081925cf}.gallery-lightbox.show{display:flex}.lightbox-card{position:relative;width:min(920px,100%);max-height:calc(100vh - 44px);padding:12px;border-radius:15px;background:#fff;box-shadow:0 20px 70px #0008}.lightbox-close{position:absolute;top:-13px;right:-13px;width:38px;height:38px;border:0;border-radius:50%;background:#fff;color:#244b60;font-size:1.45rem;line-height:1}.lightbox-card img{display:block;max-width:100%;max-height:calc(100vh - 125px);margin:auto;border-radius:9px;object-fit:contain}.lightbox-caption{padding:10px 4px 2px;color:#35596c;font-size:.86rem;font-weight:800;text-align:center}
    @media(max-width:576px){.gallery-hero h1{font-size:1.6rem}.gallery-image,.gallery-video{height:185px}}
</style>
<main class="gallery-page"><div class="container"><header class="gallery-hero"><h1>GALERI DINAS PKP MALUKU</h1><p>Dokumentasi kegiatan, publikasi informasi, dan video Dinas Perumahan dan Kawasan Permukiman Provinsi Maluku.</p></header><nav class="gallery-tabs" aria-label="Kategori galeri"><button class="gallery-tab active" data-target="all"><i class="fas fa-border-all"></i>Semua</button><button class="gallery-tab" data-target="kegiatan"><i class="fas fa-camera"></i>Galeri Kegiatan <span>({{ $galleryGroups['kegiatan']->count() }})</span></button><button class="gallery-tab" data-target="informasi"><i class="fas fa-bullhorn"></i>Galeri Informasi <span>({{ $galleryGroups['informasi']->count() }})</span></button><button class="gallery-tab" data-target="video"><i class="fas fa-play-circle"></i>Galeri Video <span>({{ $galleryGroups['video']->count() }})</span></button></nav>
@php($labels=['kegiatan'=>['Galeri Kegiatan','fas fa-camera','Dokumentasi aktivitas dan program lapangan.'],'informasi'=>['Galeri Informasi','fas fa-bullhorn','Publikasi dan materi informasi layanan.'],'video'=>['Galeri Video','fas fa-play-circle','Video dokumentasi dan informasi Dinas PKP.']])
@foreach($labels as $category => [$heading,$icon,$description])<section class="gallery-section" data-gallery-section="{{ $category }}"><h2 class="gallery-section-title"><i class="{{ $icon }}"></i><span>{{ $heading }}<small class="d-block fw-normal">{{ $description }}</small></span></h2><div class="row g-4">@forelse($galleryGroups[$category] as $gallery)@php($imageUrl=$gallery->image_path ? (str_starts_with($gallery->image_path,'assets/') ? asset($gallery->image_path) : asset('storage/'.$gallery->image_path)) : null)@php($embedUrl=$gallery->video_url ? preg_replace('~(?:https?://)?(?:www\.)?(?:youtube\.com/watch\?v=|youtu\.be/)([^&?/]+).*~', 'https://www.youtube.com/embed/$1', $gallery->video_url) : null)<div class="col-md-6 col-lg-4"><article class="gallery-card">@if($category==='video')<div class="gallery-video">@if($embedUrl && str_starts_with($embedUrl,'https://www.youtube.com/embed/'))<iframe src="{{ $embedUrl }}" title="{{ $gallery->title }}" loading="lazy" allowfullscreen></iframe>@else<a class="video-fallback" href="{{ $gallery->video_url }}" target="_blank"><i class="fas fa-play-circle"></i></a>@endif<span class="gallery-kind"><i class="fas fa-video me-1"></i>VIDEO</span></div>@elseif($imageUrl)<a class="gallery-image" href="{{ $imageUrl }}" data-lightbox data-caption="{{ $gallery->title }}"><img src="{{ $imageUrl }}" alt="{{ $gallery->title }}"><span class="gallery-kind"><i class="fas fa-image me-1"></i>{{ strtoupper($category) }}</span></a>@else<div class="gallery-image d-grid place-items-center text-secondary"><i class="fas fa-image fa-2x"></i><span class="gallery-kind">{{ strtoupper($category) }}</span></div>@endif<div class="gallery-body"><h2>{{ $gallery->title }}</h2>@if($gallery->description)<p>{{ $gallery->description }}</p>@endif</div></article></div>@empty<div class="col-12"><div class="gallery-empty">Belum ada data {{ strtolower($heading) }}.</div></div>@endforelse</div></section>@endforeach
</div></main>
<div id="galleryLightbox" class="gallery-lightbox" aria-hidden="true"><div class="lightbox-card" role="dialog" aria-modal="true"><button id="lightboxClose" class="lightbox-close" aria-label="Tutup">&times;</button><img id="lightboxImage" src="" alt=""><div id="lightboxCaption" class="lightbox-caption"></div></div></div>
<script>document.querySelectorAll('.gallery-tab').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('.gallery-tab').forEach(item=>item.classList.remove('active'));button.classList.add('active');document.querySelectorAll('[data-gallery-section]').forEach(section=>section.style.display=button.dataset.target==='all'||section.dataset.gallerySection===button.dataset.target?'block':'none')}));const lightbox=document.getElementById('galleryLightbox'),closeLightbox=()=>{lightbox.classList.remove('show');lightbox.setAttribute('aria-hidden','true')};document.querySelectorAll('[data-lightbox]').forEach(link=>link.addEventListener('click',event=>{event.preventDefault();document.getElementById('lightboxImage').src=link.href;document.getElementById('lightboxImage').alt=link.dataset.caption;document.getElementById('lightboxCaption').textContent=link.dataset.caption;lightbox.classList.add('show');lightbox.setAttribute('aria-hidden','false')}));document.getElementById('lightboxClose').onclick=closeLightbox;lightbox.onclick=event=>{if(event.target===lightbox)closeLightbox()};document.addEventListener('keydown',event=>{if(event.key==='Escape')closeLightbox()});</script>
@endsection
